// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: umoja/settlement/v1/settlement.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "umoja.settlement.v1";

export interface SettlementRequest {
  intentId: string;
  idempotencyKey: string;
  tenantId: string;
  direction: string;
  asset: string;
  fiat: string;
  amountMinor: number;
  destination: string;
  canonicalPayload: Uint8Array;
  payloadSha256: string;
  expiresAtRfc3339: string;
}

export interface SettlementQueryRequest {
  intentId: string;
  idempotencyKey: string;
  tenantId: string;
  asset: string;
  fiat: string;
  payloadSha256: string;
}

export interface SettlementResponse {
  state: string;
  reference: string;
  blockchainTx: string;
  reason: string;
  retryableWithoutEffect: boolean;
  payloadSha256: string;
  attestationId: string;
}

function createBaseSettlementRequest(): SettlementRequest {
  return {
    intentId: "",
    idempotencyKey: "",
    tenantId: "",
    direction: "",
    asset: "",
    fiat: "",
    amountMinor: 0,
    destination: "",
    canonicalPayload: new Uint8Array(0),
    payloadSha256: "",
    expiresAtRfc3339: "",
  };
}

export const SettlementRequest: MessageFns<SettlementRequest> = {
  encode(message: SettlementRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.intentId !== "") {
      writer.uint32(10).string(message.intentId);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(18).string(message.idempotencyKey);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    if (message.direction !== "") {
      writer.uint32(34).string(message.direction);
    }
    if (message.asset !== "") {
      writer.uint32(42).string(message.asset);
    }
    if (message.fiat !== "") {
      writer.uint32(50).string(message.fiat);
    }
    if (message.amountMinor !== 0) {
      writer.uint32(56).int64(message.amountMinor);
    }
    if (message.destination !== "") {
      writer.uint32(66).string(message.destination);
    }
    if (message.canonicalPayload.length !== 0) {
      writer.uint32(74).bytes(message.canonicalPayload);
    }
    if (message.payloadSha256 !== "") {
      writer.uint32(82).string(message.payloadSha256);
    }
    if (message.expiresAtRfc3339 !== "") {
      writer.uint32(90).string(message.expiresAtRfc3339);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SettlementRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettlementRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.intentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.direction = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fiat = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.amountMinor = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.destination = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.canonicalPayload = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.payloadSha256 = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.expiresAtRfc3339 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SettlementRequest {
    return {
      intentId: isSet(object.intentId) ? globalThis.String(object.intentId) : "",
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      direction: isSet(object.direction) ? globalThis.String(object.direction) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      fiat: isSet(object.fiat) ? globalThis.String(object.fiat) : "",
      amountMinor: isSet(object.amountMinor) ? globalThis.Number(object.amountMinor) : 0,
      destination: isSet(object.destination) ? globalThis.String(object.destination) : "",
      canonicalPayload: isSet(object.canonicalPayload) ? bytesFromBase64(object.canonicalPayload) : new Uint8Array(0),
      payloadSha256: isSet(object.payloadSha256) ? globalThis.String(object.payloadSha256) : "",
      expiresAtRfc3339: isSet(object.expiresAtRfc3339) ? globalThis.String(object.expiresAtRfc3339) : "",
    };
  },

  toJSON(message: SettlementRequest): unknown {
    const obj: any = {};
    if (message.intentId !== "") {
      obj.intentId = message.intentId;
    }
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.direction !== "") {
      obj.direction = message.direction;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.fiat !== "") {
      obj.fiat = message.fiat;
    }
    if (message.amountMinor !== 0) {
      obj.amountMinor = Math.round(message.amountMinor);
    }
    if (message.destination !== "") {
      obj.destination = message.destination;
    }
    if (message.canonicalPayload.length !== 0) {
      obj.canonicalPayload = base64FromBytes(message.canonicalPayload);
    }
    if (message.payloadSha256 !== "") {
      obj.payloadSha256 = message.payloadSha256;
    }
    if (message.expiresAtRfc3339 !== "") {
      obj.expiresAtRfc3339 = message.expiresAtRfc3339;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SettlementRequest>, I>>(base?: I): SettlementRequest {
    return SettlementRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SettlementRequest>, I>>(object: I): SettlementRequest {
    const message = createBaseSettlementRequest();
    message.intentId = object.intentId ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.tenantId = object.tenantId ?? "";
    message.direction = object.direction ?? "";
    message.asset = object.asset ?? "";
    message.fiat = object.fiat ?? "";
    message.amountMinor = object.amountMinor ?? 0;
    message.destination = object.destination ?? "";
    message.canonicalPayload = object.canonicalPayload ?? new Uint8Array(0);
    message.payloadSha256 = object.payloadSha256 ?? "";
    message.expiresAtRfc3339 = object.expiresAtRfc3339 ?? "";
    return message;
  },
};

function createBaseSettlementQueryRequest(): SettlementQueryRequest {
  return { intentId: "", idempotencyKey: "", tenantId: "", asset: "", fiat: "", payloadSha256: "" };
}

export const SettlementQueryRequest: MessageFns<SettlementQueryRequest> = {
  encode(message: SettlementQueryRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.intentId !== "") {
      writer.uint32(10).string(message.intentId);
    }
    if (message.idempotencyKey !== "") {
      writer.uint32(18).string(message.idempotencyKey);
    }
    if (message.tenantId !== "") {
      writer.uint32(26).string(message.tenantId);
    }
    if (message.asset !== "") {
      writer.uint32(34).string(message.asset);
    }
    if (message.fiat !== "") {
      writer.uint32(42).string(message.fiat);
    }
    if (message.payloadSha256 !== "") {
      writer.uint32(50).string(message.payloadSha256);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SettlementQueryRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettlementQueryRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.intentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.idempotencyKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.tenantId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.fiat = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payloadSha256 = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SettlementQueryRequest {
    return {
      intentId: isSet(object.intentId) ? globalThis.String(object.intentId) : "",
      idempotencyKey: isSet(object.idempotencyKey) ? globalThis.String(object.idempotencyKey) : "",
      tenantId: isSet(object.tenantId) ? globalThis.String(object.tenantId) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      fiat: isSet(object.fiat) ? globalThis.String(object.fiat) : "",
      payloadSha256: isSet(object.payloadSha256) ? globalThis.String(object.payloadSha256) : "",
    };
  },

  toJSON(message: SettlementQueryRequest): unknown {
    const obj: any = {};
    if (message.intentId !== "") {
      obj.intentId = message.intentId;
    }
    if (message.idempotencyKey !== "") {
      obj.idempotencyKey = message.idempotencyKey;
    }
    if (message.tenantId !== "") {
      obj.tenantId = message.tenantId;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.fiat !== "") {
      obj.fiat = message.fiat;
    }
    if (message.payloadSha256 !== "") {
      obj.payloadSha256 = message.payloadSha256;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SettlementQueryRequest>, I>>(base?: I): SettlementQueryRequest {
    return SettlementQueryRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SettlementQueryRequest>, I>>(object: I): SettlementQueryRequest {
    const message = createBaseSettlementQueryRequest();
    message.intentId = object.intentId ?? "";
    message.idempotencyKey = object.idempotencyKey ?? "";
    message.tenantId = object.tenantId ?? "";
    message.asset = object.asset ?? "";
    message.fiat = object.fiat ?? "";
    message.payloadSha256 = object.payloadSha256 ?? "";
    return message;
  },
};

function createBaseSettlementResponse(): SettlementResponse {
  return {
    state: "",
    reference: "",
    blockchainTx: "",
    reason: "",
    retryableWithoutEffect: false,
    payloadSha256: "",
    attestationId: "",
  };
}

export const SettlementResponse: MessageFns<SettlementResponse> = {
  encode(message: SettlementResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== "") {
      writer.uint32(10).string(message.state);
    }
    if (message.reference !== "") {
      writer.uint32(18).string(message.reference);
    }
    if (message.blockchainTx !== "") {
      writer.uint32(26).string(message.blockchainTx);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    if (message.retryableWithoutEffect !== false) {
      writer.uint32(40).bool(message.retryableWithoutEffect);
    }
    if (message.payloadSha256 !== "") {
      writer.uint32(50).string(message.payloadSha256);
    }
    if (message.attestationId !== "") {
      writer.uint32(58).string(message.attestationId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SettlementResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSettlementResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reference = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.blockchainTx = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retryableWithoutEffect = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.payloadSha256 = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.attestationId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SettlementResponse {
    return {
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      reference: isSet(object.reference) ? globalThis.String(object.reference) : "",
      blockchainTx: isSet(object.blockchainTx) ? globalThis.String(object.blockchainTx) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      retryableWithoutEffect: isSet(object.retryableWithoutEffect)
        ? globalThis.Boolean(object.retryableWithoutEffect)
        : false,
      payloadSha256: isSet(object.payloadSha256) ? globalThis.String(object.payloadSha256) : "",
      attestationId: isSet(object.attestationId) ? globalThis.String(object.attestationId) : "",
    };
  },

  toJSON(message: SettlementResponse): unknown {
    const obj: any = {};
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.reference !== "") {
      obj.reference = message.reference;
    }
    if (message.blockchainTx !== "") {
      obj.blockchainTx = message.blockchainTx;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.retryableWithoutEffect !== false) {
      obj.retryableWithoutEffect = message.retryableWithoutEffect;
    }
    if (message.payloadSha256 !== "") {
      obj.payloadSha256 = message.payloadSha256;
    }
    if (message.attestationId !== "") {
      obj.attestationId = message.attestationId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SettlementResponse>, I>>(base?: I): SettlementResponse {
    return SettlementResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SettlementResponse>, I>>(object: I): SettlementResponse {
    const message = createBaseSettlementResponse();
    message.state = object.state ?? "";
    message.reference = object.reference ?? "";
    message.blockchainTx = object.blockchainTx ?? "";
    message.reason = object.reason ?? "";
    message.retryableWithoutEffect = object.retryableWithoutEffect ?? false;
    message.payloadSha256 = object.payloadSha256 ?? "";
    message.attestationId = object.attestationId ?? "";
    return message;
  },
};

export type SettlementService = typeof SettlementService;
export const SettlementService = {
  execute: {
    path: "/umoja.settlement.v1.Settlement/Execute",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SettlementRequest): Buffer => Buffer.from(SettlementRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SettlementRequest => SettlementRequest.decode(value),
    responseSerialize: (value: SettlementResponse): Buffer => Buffer.from(SettlementResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SettlementResponse => SettlementResponse.decode(value),
  },
  query: {
    path: "/umoja.settlement.v1.Settlement/Query",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SettlementQueryRequest): Buffer =>
      Buffer.from(SettlementQueryRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): SettlementQueryRequest => SettlementQueryRequest.decode(value),
    responseSerialize: (value: SettlementResponse): Buffer => Buffer.from(SettlementResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SettlementResponse => SettlementResponse.decode(value),
  },
} as const;

export interface SettlementServer extends UntypedServiceImplementation {
  execute: handleUnaryCall<SettlementRequest, SettlementResponse>;
  query: handleUnaryCall<SettlementQueryRequest, SettlementResponse>;
}

export interface SettlementClient extends Client {
  execute(
    request: SettlementRequest,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
  execute(
    request: SettlementRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
  execute(
    request: SettlementRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
  query(
    request: SettlementQueryRequest,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
  query(
    request: SettlementQueryRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
  query(
    request: SettlementQueryRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SettlementResponse) => void,
  ): ClientUnaryCall;
}

export const SettlementClient = makeGenericClientConstructor(
  SettlementService,
  "umoja.settlement.v1.Settlement",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): SettlementClient;
  service: typeof SettlementService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
