apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka
  namespace: umojaflowos
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      secretKeyRef:
        name: umojaflowos-kafka
        key: brokers
    - name: consumerGroup
      value: ledger-gateway-v1
    - name: authType
      value: password
    - name: saslUsername
      secretKeyRef:
        name: umojaflowos-kafka
        key: sasl-username
    - name: saslPassword
      secretKeyRef:
        name: umojaflowos-kafka
        key: sasl-password
    - name: tlsEnable
      value: "true"
    - name: disableTls
      value: "false"
    - name: initialOffset
      value: oldest
scopes:
  - payment-engine
  - ledger-gateway
