#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'USAGE'
Usage: collect_staging_evidence.sh --release-sha SHA --evidence-dir DIR [--execute]

Without --execute, the script only validates prerequisites and reports blockers.
With --execute, every required staging authorization marker and protected input must
be present; no simulator or local result is promoted to staging evidence.
USAGE
  exit 2
}

RELEASE_SHA=""
EVIDENCE_DIR=""
EXECUTE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --release-sha) RELEASE_SHA=${2:?missing value}; shift 2 ;;
    --evidence-dir) EVIDENCE_DIR=${2:?missing value}; shift 2 ;;
    --execute) EXECUTE=true; shift ;;
    *) usage ;;
  esac
done
[[ "$RELEASE_SHA" =~ ^[a-f0-9]{40}$ ]] || { echo "release SHA must be lowercase 40-character SHA" >&2; exit 1; }
[[ "$EVIDENCE_DIR" = /* ]] || {
  echo "evidence directory must be an absolute approved external path" >&2
  exit 1
}
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
case "$EVIDENCE_DIR" in
  "$repo_root"|"$repo_root"/*)
    echo "evidence directory must not be inside the source repository" >&2
    exit 1
    ;;
esac
mkdir -p "$EVIDENCE_DIR"
printf 'release_sha=%s\nenvironment=staging\ncreated_at=%s\n' "$RELEASE_SHA" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" > "$EVIDENCE_DIR/collection-metadata.txt"

record_blocker() { printf '%s\tBLOCKED\t%s\n' "$1" "$2" >> "$EVIDENCE_DIR/collection-status.tsv"; }
record_ready() { printf '%s\tREADY\t%s\n' "$1" "$2" >> "$EVIDENCE_DIR/collection-status.tsv"; }
: > "$EVIDENCE_DIR/collection-status.tsv"

if [[ "$EXECUTE" != true ]]; then
  for id in E-01 E-02 E-03 E-04 E-05 E-06 E-07 E-08 E-09; do
    record_blocker "$id" "preflight-only mode; rerun with --execute only during approved staging window"
  done
  echo "preflight complete: no staging systems contacted; all items remain blocked"
  exit 1
fi

: "${STAGING_EVIDENCE_APPROVED:?set STAGING_EVIDENCE_APPROVED=EXECUTE_APPROVED_STAGING_EVIDENCE_COLLECTION}"
[[ "$STAGING_EVIDENCE_APPROVED" == EXECUTE_APPROVED_STAGING_EVIDENCE_COLLECTION ]] || { echo "invalid staging collection authorization" >&2; exit 1; }

git fetch --quiet origin --tags --prune
test "$(git rev-parse HEAD)" = "$RELEASE_SHA" || { echo "checkout does not match release SHA" >&2; exit 1; }
test -z "$(git status --porcelain)" || { echo "worktree must be clean" >&2; exit 1; }

for required in E01_TAG E01_IMAGE E01_GPG_FINGERPRINT E01_CERTIFICATE_IDENTITY E01_CERTIFICATE_ISSUER; do
  [[ -n "${!required:-}" ]] || { record_blocker E-01 "missing protected input $required"; continue; }
done
if [[ -n "${E01_TAG:-}" && -n "${E01_IMAGE:-}" && -n "${E01_GPG_FINGERPRINT:-}" && -n "${E01_CERTIFICATE_IDENTITY:-}" && -n "${E01_CERTIFICATE_ISSUER:-}" ]]; then
  scripts/infra/verify_release_cryptography.sh \
    --repo-dir . --release-sha "$RELEASE_SHA" --tag "$E01_TAG" --image "$E01_IMAGE" \
    --certificate-identity-regexp "$E01_CERTIFICATE_IDENTITY" \
    --certificate-oidc-issuer "$E01_CERTIFICATE_ISSUER" \
    --expected-gpg-fingerprint "$E01_GPG_FINGERPRINT" \
    --output-dir "$EVIDENCE_DIR/E-01"
  record_ready E-01 "$EVIDENCE_DIR/E-01"
fi

if [[ -n "${POSTGRES_DATABASE_URL:-}" && "${STAGING_E02_APPROVED:-}" == STAGING_SCHEMA_MIGRATION ]]; then
  POSTGRES_DATABASE_URL="$POSTGRES_DATABASE_URL" \
    STAGING_E02_APPROVED=STAGING_SCHEMA_MIGRATION \
    EVIDENCE_DIR="$EVIDENCE_DIR/E-02" \
    scripts/infra/run_staging_e02_schema_gate.sh
  record_ready E-02 "$EVIDENCE_DIR/E-02"
else
  record_blocker E-02 "missing protected PostgreSQL URL or STAGING_SCHEMA_MIGRATION approval"
fi

record_blocker E-03 "staging application-role evidence must be generated by the approved staging deployment"
record_blocker E-04 "requires approved TigerBeetle endpoint, 128-bit cluster ID, ledger/account inputs, TLS, and execution window"
record_blocker E-05 "requires real Keycloak/provider/AML/regulatory/WORM/notification endpoints and credentials"
record_blocker E-06 "requires approved kubeconfig, immutable image digest, and deployment authorization"
record_blocker E-07 "requires live monitoring endpoints and delivery receipts"
record_blocker E-08 "requires approved backup/restore target, Chaos window, and recovery authorization"
record_blocker E-09 "local scans are supporting evidence; independent security review remains required"

echo "collection completed with explicit status rows; inspect $EVIDENCE_DIR/collection-status.tsv"
if grep -q $'\tBLOCKED\t' "$EVIDENCE_DIR/collection-status.tsv"; then exit 1; fi
