import { getPool, type Actor } from "./postgres";

export const imtoEvidenceCategories = ["cbn_imto_licence_or_application","permitted_remittance_scope","settlement_account_and_authorised_bank","aml_cft_cpf_and_sanctions_programme","customer_disclosure_and_complaints","agent_fintech_and_partner_oversight","reconciliation_and_safeguarding","incident_reporting_and_business_continuity","controlled_test_and_wind_down"] as const;
export type ImtoEvidenceCategory = (typeof imtoEvidenceCategories)[number];

async function audit(client: any, actor: Actor, action: string, id: string, metadata: Record<string, unknown>) { await client.query("INSERT INTO activity_events (actor_subject,actor_role,action,object_type,object_id,metadata) VALUES ($1,$2,$3,'imto_readiness_profile',$4,$5::jsonb)",[actor.openId,actor.role,action,id,JSON.stringify({...metadata,authoritative:false,externalLicenceVerification:false,providerActivation:false,remittanceExecution:false,settlementExecution:false})]); }
export async function createImtoReadinessProfile(actor: Actor,input:{legalEntityId:string;operatingModelSummary:string}) { const c=await getPool().connect();try{await c.query("BEGIN");const entity=await c.query("SELECT id FROM legal_entities WHERE id=$1 AND jurisdiction='Nigeria' FOR KEY SHARE",[input.legalEntityId]);if(!entity.rows[0])throw new Error("A canonical Nigeria legal entity is required");const {rows}=await c.query<{id:string}>("INSERT INTO imto_readiness_profiles (legal_entity_id,operating_model_summary,recorded_by) VALUES ($1,$2,$3) ON CONFLICT (legal_entity_id) DO UPDATE SET operating_model_summary=EXCLUDED.operating_model_summary,recorded_by=EXCLUDED.recorded_by,recorded_at=now() RETURNING id",[input.legalEntityId,input.operatingModelSummary,actor.openId]);const r=rows[0];if(!r)throw new Error("IMTO profile was not recorded");await audit(c,actor,"imto_readiness_profile.recorded",r.id,{legalEntityId:input.legalEntityId});await c.query("COMMIT");return r;}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}
export async function recordImtoReadinessEvidence(actor: Actor,input:{profileId:string;category:ImtoEvidenceCategory;evidenceUri:string;evidenceSha256:string}) { const c=await getPool().connect();try{await c.query("BEGIN");const {rows}=await c.query<{id:string}>("INSERT INTO imto_readiness_evidence_items (profile_id,category,evidence_uri,evidence_sha256,recorded_by) VALUES ($1,$2,$3,$4,$5) ON CONFLICT (profile_id,category,evidence_sha256) DO NOTHING RETURNING id",[input.profileId,input.category,input.evidenceUri,input.evidenceSha256,actor.openId]);const id=rows[0]?.id;if(id)await audit(c,actor,"imto_readiness_evidence.recorded",input.profileId,{category:input.category,evidenceRecorded:true});await c.query("COMMIT");return{id:id??null,duplicate:!id};}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}
export async function assessImtoReadiness(actor: Actor,input:{profileId:string;reviewerRationale:string}) { const c=await getPool().connect();try{await c.query("BEGIN");const evidence=await c.query<{category:ImtoEvidenceCategory}>("SELECT DISTINCT category FROM imto_readiness_evidence_items WHERE profile_id=$1",[input.profileId]);const recorded=evidence.rows.map(x=>x.category);const missing=imtoEvidenceCategories.filter(x=>!recorded.includes(x));const outcome=missing.length?"internal_record_incomplete":"internal_record_complete_pending_external_review";const {rows}=await c.query<{id:string}>("INSERT INTO imto_readiness_assessments (profile_id,required_categories,recorded_categories,missing_categories,outcome,reviewer_rationale,assessed_by) VALUES ($1,$2::jsonb,$3::jsonb,$4::jsonb,$5,$6,$7) RETURNING id",[input.profileId,JSON.stringify(imtoEvidenceCategories),JSON.stringify(recorded),JSON.stringify(missing),outcome,input.reviewerRationale,actor.openId]);const r=rows[0];if(!r)throw new Error("IMTO assessment was not recorded");await audit(c,actor,"imto_readiness.assessed",input.profileId,{outcome,missingCategories:missing});await c.query("COMMIT");return{id:r.id,requiredCategories:[...imtoEvidenceCategories],recordedCategories:recorded,missingCategories:missing,outcome,externalLicenceVerification:false,providerActivation:false,remittanceExecution:false,settlementExecution:false};}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}
