import { describe, expect, it } from "vitest";

import { registerPostgresLegalEntity } from "./legalEntityRegistry";
import {
  createPostgresRegulatoryReport,
  listPostgresActivityEventsForObjects,
  listPostgresRegulatoryReports,
  transitionPostgresRegulatoryReport,
} from "./postgres";

const RUN_INTEGRATION = process.env.POSTGRES_INTEGRATION_TEST === "1";
const describeIntegration = RUN_INTEGRATION ? describe : describe.skip;

const administrator = { openId: `regression-report-admin-${Date.now()}`, role: "admin" as const };
const officer = { openId: `regression-report-officer-${Date.now()}`, role: "compliance_officer" as const };
const treasury = { openId: `regression-report-treasury-${Date.now()}`, role: "treasury_operator" as const };

/**
 * Each corridor's regulator with the jurisdiction its reporting entity is
 * registered in. These are the three corridors the platform serves.
 */
const CORRIDORS = [
  { regulator: "CBN" as const, corridor: "NIGERIA_NGN" as const, jurisdiction: "Nigeria" as const },
  { regulator: "CBK" as const, corridor: "KENYA_KES" as const, jurisdiction: "Kenya" as const },
  { regulator: "SARB" as const, corridor: "SOUTH_AFRICA_ZAR" as const, jurisdiction: "South Africa" as const },
];

const EVIDENCE_MANIFEST = {
  generatedBy: "python-reporting-service",
  bronzeBatches: ["regression-batch-0001"],
  rowCounts: { payment_orders: 0, payment_legs: 0 },
};

async function entityFor(jurisdiction: "Nigeria" | "Kenya" | "South Africa") {
  return registerPostgresLegalEntity(administrator, {
    legalName: `Regression Reporting Entity ${jurisdiction}`,
    jurisdiction,
    registrationIdentifier: `regression-${jurisdiction}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  });
}

describeIntegration("CBN, CBK, and SARB report lifecycle", () => {
  it("registers a reporting legal entity only through an administrator", async () => {
    await expect(
      registerPostgresLegalEntity(officer as never, {
        legalName: "Regression Unauthorised Entity",
        jurisdiction: "Nigeria",
        registrationIdentifier: `regression-denied-${Date.now()}`,
      }),
    ).rejects.toThrow(/administrator/i);
  });

  it("drafts and advances a report for each corridor regulator", async () => {
    for (const { regulator, corridor, jurisdiction } of CORRIDORS) {
      const entity = await entityFor(jurisdiction);
      const periodStart = new Date("2026-07-01T00:00:00Z");
      const periodEnd = new Date("2026-07-31T23:59:59Z");

      const draft = await createPostgresRegulatoryReport(treasury as never, {
        regulator,
        corridor,
        reportType: "monthly_cross_border_flows",
        periodStart,
        periodEnd,
        legalEntityId: entity.id,
      });
      expect(draft.status).toBe("draft");

      // A draft cannot advance without its artifact and evidence manifest.
      await expect(
        transitionPostgresRegulatoryReport(treasury as never, {
          reportId: draft.id,
          status: "under_review",
          statusReason: "Attempting review without the generated artifact must fail closed.",
        }),
      ).rejects.toThrow(/artifact uri and evidence manifest/i);

      const reviewed = await transitionPostgresRegulatoryReport(treasury as never, {
        reportId: draft.id,
        status: "under_review",
        statusReason: "Artifact generated by the Python reporting service and submitted for review.",
        artifactUri: `https://storage.example/reports/${regulator.toLowerCase()}-2026-07`,
        evidenceManifest: EVIDENCE_MANIFEST,
      });
      expect(reviewed.status).toBe("under_review");

      // Approval is the compliance officer's decision, not the preparer's.
      await expect(
        transitionPostgresRegulatoryReport(treasury as never, {
          reportId: draft.id,
          status: "approved",
          statusReason: "A treasury preparer must not approve the return they prepared.",
        }),
      ).rejects.toThrow(/compliance officer/i);

      const approved = await transitionPostgresRegulatoryReport(officer as never, {
        reportId: draft.id,
        status: "approved",
        statusReason: "Reviewed against the evidence manifest and approved for submission.",
      });
      expect(approved.status).toBe("approved");

      // Submitted status requires an attributable submission reference from the
      // authorised channel, which is unavailable until that channel is connected.
      await expect(
        transitionPostgresRegulatoryReport(officer as never, {
          reportId: draft.id,
          status: "submitted",
          statusReason: "Marking submitted without a channel reference must fail closed.",
        }),
      ).rejects.toThrow(/submission reference/i);

      const events = await listPostgresActivityEventsForObjects([draft.id]);
      const actions = events.map(event => event.action);
      expect(actions).toContain("regulatory_report.drafted");
      expect(actions).toContain("regulatory_report.under_review");
      expect(actions).toContain("regulatory_report.approved");
      // No submission occurred, so no submitted event exists.
      expect(actions).not.toContain("regulatory_report.submitted");
    }
  });

  it("rejects an inverted reporting period", async () => {
    const entity = await entityFor("Nigeria");
    await expect(
      createPostgresRegulatoryReport(treasury as never, {
        regulator: "CBN",
        corridor: "NIGERIA_NGN",
        reportType: "monthly_cross_border_flows",
        periodStart: new Date("2026-07-31T00:00:00Z"),
        periodEnd: new Date("2026-07-01T00:00:00Z"),
        legalEntityId: entity.id,
      }),
    ).rejects.toThrow(/period end must not precede/i);
  });

  it("rejects a draft against an unknown legal entity", async () => {
    await expect(
      createPostgresRegulatoryReport(treasury as never, {
        regulator: "SARB",
        corridor: "SOUTH_AFRICA_ZAR",
        reportType: "monthly_cross_border_flows",
        periodStart: new Date("2026-07-01T00:00:00Z"),
        periodEnd: new Date("2026-07-31T00:00:00Z"),
        legalEntityId: "00000000-0000-4000-8000-000000000000",
      }),
    ).rejects.toThrow(/legal entity was not found/i);
  });

  it("exposes every corridor's report as auditor-readable with its status", async () => {
    const reports = await listPostgresRegulatoryReports();
    const regulators = new Set(reports.map(row => row.regulator));
    for (const { regulator } of CORRIDORS) expect(regulators.has(regulator)).toBe(true);
  });
});
