apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../payment-engine-mojaloop-secure.yaml
patches:
  - path: service-grpc-port.patch.yaml
  - path: deployment-grpc-port-and-tls.patch.yaml
