apiVersion: v1
kind: Service
metadata:
  name: payment-engine
  namespace: umoja-payment
spec:
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
    - name: grpc-tls
      port: 8443
      targetPort: grpc-tls
      protocol: TCP
