import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import type { OperatorRole } from "@/lib/roleCapabilities";
import { AlertTriangle, FileCheck2, ShieldAlert } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

const evidenceCategories = ["corporate_governance", "ownership", "financial_capacity", "aml_cft_cpf", "consumer_protection", "cybersecurity", "data_protection", "operational_resilience", "business_continuity", "stablecoin_governance", "reserve_attestation", "redemption", "custody_key_management", "third_party_oversight", "testing_plan"] as const;

function ControlNotice() {
  return <div className="border-b border-[#e11919]/30 bg-[#e11919]/5 px-5 py-4"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#e11919]" /><div><p className="text-sm font-black uppercase tracking-tight">Evidence-only CBN readiness workspace</p><p className="mt-1 max-w-4xl text-xs leading-5 text-black/65">This workspace records supplied application evidence and controlled-test planning for Nigeria (NGN). It does not submit to CBN, prove admission or licensing, activate a provider, initiate a payment, settle value, or notify an external authority.</p></div></div></div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">{label}</span>{children}</label>; }
function Empty({ title, detail }: { title: string; detail: string }) { return <div className="px-5 py-8"><p className="font-bold">{title}</p><p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">{detail}</p></div>; }

export function CbnSandboxWorkspace({ role }: { role: OperatorRole | undefined }) {
  const utils = trpc.useUtils();
  const dossiers = trpc.postgres.cbnSandboxDossiers.useQuery();
  const legalEntities = trpc.postgres.legalEntities.useQuery();
  const customers = trpc.postgres.customers.useQuery();
  const [selectedId, setSelectedId] = useState("");
  const [form, setForm] = useState<"dossier" | "evidence" | "plan" | "consumer" | "incident" | "pack" | null>(null);
  const readiness = trpc.postgres.cbnSandboxReadiness.useQuery({ dossierId: selectedId }, { enabled: selectedId !== "" });
  const canAdmin = role === "admin";
  const canCompliance = role === "compliance_officer" || role === "admin";

  useEffect(() => { if (!selectedId && dossiers.data?.[0]?.id) setSelectedId(dossiers.data[0].id); }, [dossiers.data, selectedId]);
  const refresh = async () => { await Promise.all([utils.postgres.cbnSandboxDossiers.invalidate(), utils.postgres.cbnSandboxReadiness.invalidate()]); };
  const close = async (message: string) => { toast.success(message); setForm(null); await refresh(); };
  const createDossier = trpc.postgres.createCbnSandboxDossier.useMutation({ onSuccess: () => void close("CBN readiness dossier recorded; no external submission has occurred."), onError: error => toast.error(error.message) });
  const recordEvidence = trpc.postgres.recordCbnSandboxEvidence.useMutation({ onSuccess: () => void close("Supplied evidence reference recorded without asserting verification."), onError: error => toast.error(error.message) });
  const createPlan = trpc.postgres.createCbnSandboxTestPlan.useMutation({ onSuccess: () => void close("Controlled-test plan documented; it remains non-executable."), onError: error => toast.error(error.message) });
  const recordConsumer = trpc.postgres.recordCbnSandboxConsumerRecord.useMutation({ onSuccess: () => void close("Consumer record retained with no external notification claim."), onError: error => toast.error(error.message) });
  const recordIncident = trpc.postgres.recordCbnSandboxIncident.useMutation({ onSuccess: () => void close("Incident recorded as not submitted to an external authority."), onError: error => toast.error(error.message) });
  const createPack = trpc.postgres.createCbnSandboxReportingPack.useMutation({ onSuccess: () => void close("Reporting pack assembled from recorded evidence as not submitted."), onError: error => toast.error(error.message) });

  const requireDossier = () => { if (!selectedId) { toast.error("Select a CBN readiness dossier first."); return false; } return true; };
  const mutationPending = createDossier.isPending || recordEvidence.isPending || createPlan.isPending || recordConsumer.isPending || recordIncident.isPending || createPack.isPending;
  return <div className="grid gap-5"><ControlNotice />
    <div className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><section className="uf-panel"><div className="border-b border-black/20 px-5 py-4"><p className="uf-kicker">CBN Cohort 2</p><h2 className="mt-1 text-lg font-black uppercase tracking-[-0.045em]">Readiness dossier</h2></div><div className="p-5"><Field label="Recorded dossier"><select aria-label="CBN sandbox dossier" className="h-10 w-full rounded-none border border-black/25 bg-white px-2 text-sm" value={selectedId} onChange={event => setSelectedId(event.target.value)}><option value="">Select a dossier</option>{(dossiers.data ?? []).map(dossier => <option key={dossier.id} value={dossier.id}>{dossier.legalEntityName} · {dossier.track.replaceAll("_", " ")}</option>)}</select></Field><div className="mt-4 flex flex-wrap gap-2">{canAdmin ? <Button className="rounded-none bg-[#e11919] text-xs font-black uppercase hover:bg-black" onClick={() => setForm("dossier")}>New dossier</Button> : null}{canCompliance ? <><Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={() => requireDossier() && setForm("evidence")}>Evidence</Button><Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={() => requireDossier() && setForm("incident")}>Incident</Button></> : null}{canAdmin ? <Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={() => requireDossier() && setForm("plan")}>Test plan</Button> : null}{canCompliance ? <><Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={() => requireDossier() && setForm("consumer")}>Consumer record</Button><Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={() => requireDossier() && setForm("pack")}>Reporting pack</Button></> : null}</div></div></section>
      <section className="uf-panel"><div className="border-b border-black/20 px-5 py-4"><p className="uf-kicker">Truthful status</p><h2 className="mt-1 text-lg font-black uppercase tracking-[-0.045em]">External review remains required</h2></div>{readiness.isLoading ? <Empty title="Loading readiness" detail="Retrieving only recorded CBN dossier evidence." /> : readiness.data ? <div className="grid gap-4 p-5"><div className="grid gap-3 sm:grid-cols-2"><Status label="Evidence state" value={readiness.data.readiness.replaceAll("_", " ")} /><Status label="Documented test plan" value={readiness.data.documentedTestPlan ? "recorded" : "missing"} /><Status label="External submission" value="not submitted" /><Status label="CBN admission / licence" value="not claimed" /></div>{readiness.data.missingEvidenceCategories.length ? <div className="border border-[#e11919]/30 bg-[#e11919]/5 p-4"><div className="flex gap-2"><AlertTriangle className="h-4 w-4 shrink-0 text-[#e11919]" /><div><p className="text-sm font-bold">Evidence remains incomplete</p><p className="mt-1 text-xs leading-5 text-black/65">Missing recorded categories: {readiness.data.missingEvidenceCategories.map(value => value.replaceAll("_", " ")).join(", ")}.</p></div></div></div> : <div className="border border-black/15 bg-black/[0.02] p-4 text-sm leading-6">The required evidence categories and a plan are recorded. This indicates only internal dossier completeness pending external review; it is not a CBN decision.</div>}</div> : <Empty title="No CBN dossier selected" detail="Create or select a Nigeria (NGN) dossier to view only its recorded readiness state." />}</section></div>
    {form === "dossier" && <Form title="New CBN Cohort 2 readiness dossier" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); createDossier.mutate({ legalEntityId: String(data.get("legalEntityId")), track: String(data.get("track")) as "vasp" | "data_enabled_non_vasp", productName: String(data.get("productName")), productSummary: String(data.get("productSummary")) }); }}><Field label="Nigeria legal entity"><select name="legalEntityId" required className="h-10 rounded-none border border-black/25 bg-white px-2">{(legalEntities.data ?? []).filter(entity => entity.jurisdiction === "Nigeria").map(entity => <option key={entity.id} value={entity.id}>{entity.legalName}</option>)}</select></Field><Field label="Track"><select name="track" className="h-10 rounded-none border border-black/25 bg-white px-2"><option value="vasp">VASP</option><option value="data_enabled_non_vasp">Data-enabled financial services</option></select></Field><Field label="Product name"><Input name="productName" required minLength={3} /></Field><Field label="Product summary"><textarea name="productSummary" required minLength={50} className="min-h-28 rounded-none border border-black/25 p-2 text-sm" /></Field></Form>}
    {form === "evidence" && <Form title="Record supplied evidence reference" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); recordEvidence.mutate({ dossierId: selectedId, category: String(data.get("category")) as typeof evidenceCategories[number], evidenceUri: String(data.get("evidenceUri")), evidenceSha256: String(data.get("evidenceSha256")) }); }}><Field label="Evidence category"><select name="category" className="h-10 rounded-none border border-black/25 bg-white px-2">{evidenceCategories.map(category => <option key={category} value={category}>{category.replaceAll("_", " ")}</option>)}</select></Field><Field label="HTTPS evidence URI"><Input name="evidenceUri" type="url" required placeholder="https://…" /></Field><Field label="SHA-256 digest"><Input name="evidenceSha256" required pattern="[a-f0-9]{64}" placeholder="64 lowercase hexadecimal characters" /></Field></Form>}
    {form === "plan" && <Form title="Document controlled-test boundaries" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); createPlan.mutate({ dossierId: selectedId, permittedUse: String(data.get("permittedUse")), userCategory: String(data.get("userCategory")), maxTransactions: Number(data.get("maxTransactions")), maxAggregateExposure: String(data.get("maxAggregateExposure")), startsAt: new Date(String(data.get("startsAt"))), endsAt: new Date(String(data.get("endsAt"))), successMetricsUri: String(data.get("successMetricsUri")), windDownUri: String(data.get("windDownUri")) }); }}><Field label="Permitted use"><textarea name="permittedUse" required minLength={20} className="min-h-20 rounded-none border border-black/25 p-2 text-sm" /></Field><Field label="User category"><Input name="userCategory" required /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Maximum transactions"><Input name="maxTransactions" type="number" min="1" required /></Field><Field label="Maximum aggregate exposure"><Input name="maxAggregateExposure" inputMode="decimal" pattern="\d+(\.\d{1,12})?" required /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Start"><Input name="startsAt" type="datetime-local" required /></Field><Field label="End"><Input name="endsAt" type="datetime-local" required /></Field></div><Field label="Success metrics URI"><Input name="successMetricsUri" type="url" required placeholder="https://…" /></Field><Field label="Orderly wind-down URI"><Input name="windDownUri" type="url" required placeholder="https://…" /></Field></Form>}
    {form === "consumer" && <Form title="Record consumer disclosure or complaint" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); recordConsumer.mutate({ dossierId: selectedId, customerId: String(data.get("customerId")), recordKind: String(data.get("recordKind")) as "disclosure_acceptance" | "complaint", disclosureVersion: String(data.get("disclosureVersion")) || undefined, evidenceUri: String(data.get("evidenceUri")), details: String(data.get("details")) }); }}><Field label="Customer"><select name="customerId" required className="h-10 rounded-none border border-black/25 bg-white px-2">{(customers.data ?? []).map(customer => <option key={customer.id} value={customer.id}>{customer.legalName}</option>)}</select></Field><Field label="Record type"><select name="recordKind" className="h-10 rounded-none border border-black/25 bg-white px-2"><option value="disclosure_acceptance">Disclosure acceptance</option><option value="complaint">Complaint</option></select></Field><Field label="Disclosure version (required for acceptance)"><Input name="disclosureVersion" /></Field><Field label="HTTPS evidence URI"><Input name="evidenceUri" type="url" required placeholder="https://…" /></Field><Field label="Details"><textarea name="details" required minLength={10} className="min-h-20 rounded-none border border-black/25 p-2 text-sm" /></Field></Form>}
    {form === "incident" && <Form title="Record material incident" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); recordIncident.mutate({ dossierId: selectedId, kind: String(data.get("kind")) as "cybersecurity" | "fraud" | "consumer_harm" | "operational_resilience", severity: String(data.get("severity")) as "low" | "medium" | "high" | "critical", occurredAt: new Date(String(data.get("occurredAt"))), detectedAt: new Date(String(data.get("detectedAt"))), evidenceUri: String(data.get("evidenceUri")), summary: String(data.get("summary")) }); }}><div className="grid gap-4 sm:grid-cols-2"><Field label="Incident type"><select name="kind" className="h-10 rounded-none border border-black/25 bg-white px-2"><option value="cybersecurity">Cybersecurity</option><option value="fraud">Fraud</option><option value="consumer_harm">Consumer harm</option><option value="operational_resilience">Operational resilience</option></select></Field><Field label="Severity"><select name="severity" className="h-10 rounded-none border border-black/25 bg-white px-2"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Occurred"><Input name="occurredAt" type="datetime-local" required /></Field><Field label="Detected"><Input name="detectedAt" type="datetime-local" required /></Field></div><Field label="HTTPS evidence URI"><Input name="evidenceUri" type="url" required placeholder="https://…" /></Field><Field label="Summary"><textarea name="summary" required minLength={20} className="min-h-20 rounded-none border border-black/25 p-2 text-sm" /></Field></Form>}
    {form === "pack" && <Form title="Assemble CBN sandbox reporting pack" pending={mutationPending} onClose={() => setForm(null)} onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); createPack.mutate({ dossierId: selectedId, periodStart: new Date(String(data.get("periodStart"))), periodEnd: new Date(String(data.get("periodEnd"))), artifactUri: String(data.get("artifactUri")) }); }}><p className="text-sm leading-6 text-black/60">The server hashes only recorded dossier evidence, incident metadata, and consumer records for the chosen period. This creates a pack in <strong>not submitted</strong> status.</p><div className="grid gap-4 sm:grid-cols-2"><Field label="Period start"><Input name="periodStart" type="datetime-local" required /></Field><Field label="Period end"><Input name="periodEnd" type="datetime-local" required /></Field></div><Field label="HTTPS artifact URI"><Input name="artifactUri" type="url" required placeholder="https://…" /></Field></Form>}
  </div>;
}

function Status({ label, value }: { label: string; value: string }) { return <div className="border border-black/15 p-3"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-black/45">{label}</p><p className="mt-2 text-sm font-bold capitalize">{value}</p></div>; }
function Form({ title, pending, onClose, onSubmit, children }: { title: string; pending: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: React.ReactNode }) { return <section className="uf-panel"><div className="flex items-start justify-between gap-4 border-b border-black/20 px-5 py-4"><div><p className="uf-kicker">Controlled record</p><h2 className="mt-1 text-lg font-black uppercase tracking-[-0.045em]">{title}</h2></div><Button variant="outline" className="rounded-none text-xs font-black uppercase" onClick={onClose}>Close</Button></div><form className="grid gap-4 p-5" onSubmit={onSubmit}>{children}<Button type="submit" disabled={pending} className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Recording…" : "Record without external claim"}</Button></form></section>; }
