import { Button } from "@/components/ui/button";
import { FormEvent, useState } from "react";

type Regulator = "CBN" | "CBK" | "SARB" | "SEC" | "CMA" | "FSCA" | "FIC";

export function CounterpartyAuthorizationTable({ rows, loading, canManage = false, transition, pending = false }: { rows: Array<{ authorization: { id: number; regulator: string; licenceReference: string; status: string; validFrom: Date; validTo: Date | null }; counterpartyName: string }>; loading: boolean; canManage?: boolean; transition?: (authorizationId: number, status: "pending_review" | "verified" | "expired" | "suspended" | "rejected") => void; pending?: boolean }) {
  if (loading) return <p className="px-5 py-8 text-sm text-black/55">Loading licence authorisation evidence.</p>;
  if (!rows.length) return <p className="px-5 py-8 text-sm text-black/55">No licence authorisation evidence is recorded for registered counterparties.</p>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Counterparty</th><th className="px-4 py-3">Regulator</th><th className="px-4 py-3">Licence</th><th className="px-4 py-3">Valid from</th><th className="px-4 py-3">State</th>{canManage && <th className="px-4 py-3">Lifecycle</th>}</tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.authorization.id}><td className="px-5 py-3 font-bold">{row.counterpartyName}</td><td className="px-4 py-3">{row.authorization.regulator}</td><td className="px-4 py-3">{row.authorization.licenceReference}</td><td className="px-4 py-3">{new Date(row.authorization.validFrom).toLocaleDateString()}</td><td className="px-4 py-3 font-bold uppercase">{row.authorization.status.replaceAll("_", " ")}</td>{canManage && <td className="px-4 py-3"><select aria-label={`Set lifecycle for ${row.counterpartyName}`} disabled={pending} defaultValue={row.authorization.status} onChange={event => transition?.(row.authorization.id, event.target.value as "pending_review" | "verified" | "expired" | "suspended" | "rejected")} className="h-8 border border-black/25 bg-white px-2 text-xs"><option value="pending_review">Pending review</option><option value="verified">Verified</option><option value="expired">Expired</option><option value="suspended">Suspended</option><option value="rejected">Rejected</option></select></td>}</tr>)}</tbody></table></div>;
}

export function CounterpartyAuthorizationForm({ counterparties, submit, pending }: { counterparties: Array<{ id: number; legalName: string }>; submit: (input: { counterpartyId: number; regulator: Regulator; licenceReference: string; scopeDescription: string; evidenceUrl: string; validFrom: Date; validTo?: Date; status: "pending_review" | "verified" | "expired" | "suspended" | "rejected" }) => void; pending: boolean }) {
  const [regulator, setRegulator] = useState<Regulator>("CBN");
  if (!counterparties.length) return <p className="px-5 py-8 text-sm leading-6 text-black/55">Register a counterparty before adding its licence authorisation evidence.</p>;
  const onSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const validTo = String(data.get("validTo") ?? "");
    submit({ counterpartyId: Number(data.get("counterpartyId")), regulator, licenceReference: String(data.get("licenceReference")), scopeDescription: String(data.get("scopeDescription")), evidenceUrl: String(data.get("evidenceUrl")), validFrom: new Date(String(data.get("validFrom"))), validTo: validTo ? new Date(validTo) : undefined, status: "pending_review" });
  };
  return <form onSubmit={onSubmit} className="grid gap-4 p-5"><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Counterparty</span><select name="counterpartyId" className="h-9 border border-black/25 bg-white px-3 text-sm">{counterparties.map(item => <option key={item.id} value={item.id}>{item.legalName}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Regulator</span><select value={regulator} onChange={event => setRegulator(event.target.value as Regulator)} className="h-9 border border-black/25 bg-white px-3 text-sm">{["CBN", "CBK", "SARB", "SEC", "CMA", "FSCA", "FIC"].map(value => <option key={value} value={value}>{value}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Licence reference</span><input name="licenceReference" required className="h-9 border border-black/25 bg-white px-3 text-sm" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Scope</span><textarea name="scopeDescription" required minLength={10} className="min-h-20 border border-black/25 bg-white px-3 py-2 text-sm" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Primary evidence URL</span><input name="evidenceUrl" type="url" required className="h-9 border border-black/25 bg-white px-3 text-sm" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Valid from</span><input name="validFrom" type="date" required className="h-9 border border-black/25 bg-white px-3 text-sm" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Valid to (optional)</span><input name="validTo" type="date" className="h-9 border border-black/25 bg-white px-3 text-sm" /></label><Button type="submit" disabled={pending} className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Saving…" : "Record licence evidence"}</Button></form>;
}
