import { Button } from "@/components/ui/button";
import { FormEvent, useState } from "react";

type DocumentType = "registration_certificate" | "identity_document" | "proof_of_address" | "beneficial_ownership" | "source_of_funds" | "other";
type MimeType = "application/pdf" | "image/jpeg" | "image/png" | "image/webp" | "image/tiff";
const allowedMimes = new Set<MimeType>(["application/pdf", "image/jpeg", "image/png", "image/webp", "image/tiff"]);
const maxBytes = 26_214_400;
async function sha256(file: File) { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return Array.from(new Uint8Array(digest), byte => byte.toString(16).padStart(2, "0")).join(""); }

export function KycDocumentUploadForm({ customers, createIntent, finalize, onComplete }: { customers: Array<{ id: string; legalName: string; kycStatus: string }>; createIntent: (input: { customerId: string; documentType: DocumentType; originalFilename: string; mimeType: MimeType; sizeBytes: number; contentSha256: string }) => Promise<{ id: string; uploadUrl: string }>; finalize: (input: { uploadIntentId: string }) => Promise<unknown>; onComplete: () => Promise<void> | void }) {
  const [documentType, setDocumentType] = useState<DocumentType>("identity_document"); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  const onSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget), file = data.get("document"); if (!(file instanceof File) || file.size === 0) { setError("Select a non-empty authorised document file."); return; } if (file.size > maxBytes) { setError("The document exceeds the 25 MiB secure-upload limit."); return; } if (!allowedMimes.has(file.type as MimeType)) { setError("Only PDF, JPEG, PNG, WEBP, and TIFF evidence files are accepted."); return; } setPending(true); setError(null); try { const intent = await createIntent({ customerId: String(data.get("customerId")), documentType, originalFilename: file.name, mimeType: file.type as MimeType, sizeBytes: file.size, contentSha256: await sha256(file) }); const upload = await fetch(intent.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error(`Secure document upload failed (${upload.status})`); await finalize({ uploadIntentId: intent.id }); event.currentTarget.reset(); await onComplete(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Secure document upload could not be completed."); } finally { setPending(false); } };
  if (!customers.length) return <p className="px-5 py-8 text-sm leading-6 text-black/55">A KYC document can only be accepted for an existing canonical customer; no customer record is currently available.</p>;
  return <form onSubmit={onSubmit} className="grid gap-4 p-5"><p className="text-xs leading-5 text-black/60">The file is uploaded directly to protected object storage. PostgreSQL receives storage metadata, checksum, review state, and immutable audit evidence—never document bytes.</p><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Customer</span><select name="customerId" className="h-9 border border-black/25 bg-white px-3 text-sm">{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.legalName} · {customer.kycStatus.replaceAll("_", " ")}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Evidence class</span><select value={documentType} onChange={event => setDocumentType(event.target.value as DocumentType)} className="h-9 border border-black/25 bg-white px-3 text-sm">{["registration_certificate", "identity_document", "proof_of_address", "beneficial_ownership", "source_of_funds", "other"].map(value => <option key={value} value={value}>{value.replaceAll("_", " ")}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Authorised evidence file</span><input name="document" type="file" required accept="application/pdf,image/jpeg,image/png,image/webp,image/tiff" className="block h-10 w-full border border-black/25 bg-white px-2 py-1 text-sm file:mr-3 file:border-0 file:bg-black file:px-3 file:py-1 file:text-xs file:font-bold file:text-white" /></label>{error && <p role="alert" className="border-l-2 border-[#e11919] px-3 text-sm text-[#a40000]">{error}</p>}<Button type="submit" disabled={pending} className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Uploading and verifying…" : "Store document evidence"}</Button></form>;
}
