import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FormEvent, useState } from "react";
import { SubmitFeedback, useRetryableSubmit, useSubmitFeedback } from "@/components/SubmitFeedback";

type Corridor = "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR";
type Regulator = "CBN" | "CBK" | "SARB";

export function PostgresReportDraftForm({ pending, submit, error, legalEntities }: { pending: boolean; submit: (input: { regulator: Regulator; corridor: Corridor; reportType: string; periodStart: Date; periodEnd: Date; legalEntityId: string }) => void; error?: string | null; legalEntities: Array<{ id: string; legalName: string }> }) {
  const [corridor, setCorridor] = useState<Corridor>("NIGERIA_NGN"); const [regulator, setRegulator] = useState<Regulator>("CBN");
  const feedback = useSubmitFeedback(pending, error);
  // Retry resends the payload that actually failed, not whatever the
  // form contains at the moment the button is pressed.
  const retryable = useRetryableSubmit(submit);
  const submitOnce = retryable.run;
  const onSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); submitOnce({ regulator, corridor, reportType: String(data.get("reportType")), periodStart: new Date(String(data.get("periodStart"))), periodEnd: new Date(String(data.get("periodEnd"))), legalEntityId: String(data.get("legalEntityId")) }); };
  return <form className="grid gap-4 p-5" onSubmit={onSubmit}><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Regulator</span><select value={regulator} onChange={event => setRegulator(event.target.value as Regulator)} className="h-9 border border-black/25 bg-white px-3 text-sm"><option value="CBN">CBN</option><option value="CBK">CBK</option><option value="SARB">SARB</option></select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Corridor</span><select value={corridor} onChange={event => setCorridor(event.target.value as Corridor)} className="h-9 border border-black/25 bg-white px-3 text-sm"><option value="NIGERIA_NGN">Nigeria (NGN)</option><option value="KENYA_KES">Kenya (KES)</option><option value="SOUTH_AFRICA_ZAR">South Africa (ZAR)</option></select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Registered legal entity</span><select name="legalEntityId" required defaultValue={legalEntities[0]?.id ?? ""} className="h-9 border border-black/25 bg-white px-3 text-sm">{legalEntities.map(entity => <option key={entity.id} value={entity.id}>{entity.legalName}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Report type</span><Input name="reportType" required className="rounded-none" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Period start</span><Input name="periodStart" required type="date" className="rounded-none" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Period end</span><Input name="periodEnd" required type="date" className="rounded-none" /></label><SubmitFeedback state={feedback} onRetry={retryable.retry} /><Button disabled={pending} type="submit" className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Saving…" : "Create report draft"}</Button></form>;
}
