import { Button } from "@/components/ui/button";
import { FormEvent, useState } from "react";

type Corridor = "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR";
type FilingType = "sar" | "str";
type FilingStatus = "under_review" | "approved_for_submission" | "pending_submission" | "submitted" | "submission_unavailable" | "rejected";

const allowedTransitions: Record<string, FilingStatus[]> = { draft: ["under_review"], under_review: ["approved_for_submission", "rejected"], approved_for_submission: ["pending_submission"], pending_submission: ["submitted", "submission_unavailable"], submission_unavailable: ["pending_submission"] };
function pretty(value: string) { return value.replaceAll("_", " "); }

export function SarStrFilingForm({ cases, pending, submit }: { cases: Array<{ id: string; caseType: string; sourceReference: string }>; pending: boolean; submit: (input: { complianceCaseId: string; corridor: Corridor; filingType: FilingType; filingAuthority: string; sourceReference: string }) => void }) {
  const [corridor, setCorridor] = useState<Corridor>("NIGERIA_NGN"); const [filingType, setFilingType] = useState<FilingType>("sar");
  const onSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); submit({ complianceCaseId: String(data.get("complianceCaseId")), corridor, filingType, filingAuthority: String(data.get("filingAuthority")), sourceReference: String(data.get("sourceReference")) }); };
  if (!cases.length) return <p className="px-5 py-8 text-sm leading-6 text-black/55">A SAR/STR filing draft can only reference an existing canonical compliance case; no case is currently available.</p>;
  return <form onSubmit={onSubmit} className="grid gap-4 p-5"><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Compliance case</span><select name="complianceCaseId" className="h-9 border border-black/25 bg-white px-3 text-sm">{cases.map(item => <option key={item.id} value={item.id}>{item.caseType.replaceAll("_", " ")} · {item.id.slice(0, 8)}</option>)}</select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Corridor</span><select value={corridor} onChange={event => setCorridor(event.target.value as Corridor)} className="h-9 border border-black/25 bg-white px-3 text-sm"><option value="NIGERIA_NGN">Nigeria (NGN)</option><option value="KENYA_KES">Kenya (KES)</option><option value="SOUTH_AFRICA_ZAR">South Africa (ZAR)</option></select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Filing classification</span><select value={filingType} onChange={event => setFilingType(event.target.value as FilingType)} className="h-9 border border-black/25 bg-white px-3 text-sm"><option value="sar">SAR</option><option value="str">STR</option></select></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Filing authority</span><input name="filingAuthority" required minLength={2} className="h-9 border border-black/25 bg-white px-3 text-sm" placeholder="Authoritative recipient name" /></label><label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">Source evidence reference</span><input name="sourceReference" required minLength={4} className="h-9 border border-black/25 bg-white px-3 text-sm" placeholder="Immutable case or filing evidence reference" /></label><Button type="submit" disabled={pending} className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Recording…" : "Create SAR/STR draft"}</Button></form>;
}

export function SarStrFilingTable({ rows, loading, canManage, pending, transition }: { rows: Array<{ id: string; corridor: string; filingType: string; filingAuthority: string; sourceReference: string; status: string; submissionReference: string | null; createdAt: Date }>; loading: boolean; canManage: boolean; pending: boolean; transition: (input: { filingId: string; status: FilingStatus; submissionReference?: string }) => void }) {
  if (loading) return <p className="px-5 py-8 text-sm text-black/55">Loading canonical PostgreSQL SAR/STR filing records.</p>;
  if (!rows.length) return <p className="px-5 py-8 text-sm leading-6 text-black/55">No SAR/STR filing is recorded. A draft begins only with attributable compliance-case and source evidence; official submission remains provider-gated.</p>;
  return <div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Corridor</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Authority</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Submission evidence</th>{canManage && <th className="px-4 py-3">Lifecycle</th>}</tr></thead><tbody>{rows.map(row => { const states = allowedTransitions[row.status] ?? []; return <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{pretty(row.corridor)}</td><td className="px-4 py-3 font-bold uppercase">{row.filingType}</td><td className="px-4 py-3">{row.filingAuthority}</td><td className="px-4 py-3 font-bold uppercase">{pretty(row.status)}</td><td className="px-4 py-3">{row.submissionReference ?? "—"}</td>{canManage && <td className="px-4 py-3">{states.length ? <select aria-label={`Transition ${row.filingType} filing`} disabled={pending} defaultValue="" onChange={event => { const status = event.target.value as FilingStatus; if (!status) return; const submissionReference = status === "submitted" ? window.prompt("Enter the verified official submission reference") ?? undefined : undefined; if (status !== "submitted" || submissionReference?.trim()) transition({ filingId: row.id, status, submissionReference }); event.currentTarget.value = ""; }} className="h-8 border border-black/25 bg-white px-2 text-xs"><option value="">Select transition</option>{states.map(state => <option key={state} value={state}>{pretty(state)}</option>)}</select> : <span className="text-black/45">Terminal</span>}</td>}</tr>; })}</tbody></table></div>;
}
