# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: umoja/settlement/v1/settlement.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'umoja/settlement/v1/settlement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$umoja/settlement/v1/settlement.proto\x12\x13umoja.settlement.v1\"\xfc\x01\n\x11SettlementRequest\x12\x11\n\tintent_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\x11\n\tdirection\x18\x04 \x01(\t\x12\r\n\x05\x61sset\x18\x05 \x01(\t\x12\x0c\n\x04\x66iat\x18\x06 \x01(\t\x12\x14\n\x0c\x61mount_minor\x18\x07 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x08 \x01(\t\x12\x19\n\x11\x63\x61nonical_payload\x18\t \x01(\x0c\x12\x16\n\x0epayload_sha256\x18\n \x01(\t\x12\x1a\n\x12\x65xpires_at_rfc3339\x18\x0b \x01(\t\"\x8c\x01\n\x16SettlementQueryRequest\x12\x11\n\tintent_id\x18\x01 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\x12\r\n\x05\x61sset\x18\x04 \x01(\t\x12\x0c\n\x04\x66iat\x18\x05 \x01(\t\x12\x16\n\x0epayload_sha256\x18\x06 \x01(\t\"\xaf\x01\n\x12SettlementResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x11\n\treference\x18\x02 \x01(\t\x12\x15\n\rblockchain_tx\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12 \n\x18retryable_without_effect\x18\x05 \x01(\x08\x12\x16\n\x0epayload_sha256\x18\x06 \x01(\t\x12\x16\n\x0e\x61ttestation_id\x18\x07 \x01(\t2\xc7\x01\n\nSettlement\x12Z\n\x07\x45xecute\x12&.umoja.settlement.v1.SettlementRequest\x1a\'.umoja.settlement.v1.SettlementResponse\x12]\n\x05Query\x12+.umoja.settlement.v1.SettlementQueryRequest\x1a\'.umoja.settlement.v1.SettlementResponseBiZggithub.com/munisp/UmojaFlowOS/services/payment-engine/internal/settlement/gen/settlementv1;settlementv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'umoja.settlement.v1.settlement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Zggithub.com/munisp/UmojaFlowOS/services/payment-engine/internal/settlement/gen/settlementv1;settlementv1'
  _globals['_SETTLEMENTREQUEST']._serialized_start=62
  _globals['_SETTLEMENTREQUEST']._serialized_end=314
  _globals['_SETTLEMENTQUERYREQUEST']._serialized_start=317
  _globals['_SETTLEMENTQUERYREQUEST']._serialized_end=457
  _globals['_SETTLEMENTRESPONSE']._serialized_start=460
  _globals['_SETTLEMENTRESPONSE']._serialized_end=635
  _globals['_SETTLEMENT']._serialized_start=638
  _globals['_SETTLEMENT']._serialized_end=837
# @@protoc_insertion_point(module_scope)
