CREATE TABLE vasp_offshore_counterparty_profiles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), dossier_id uuid NOT NULL REFERENCES cbn_sandbox_dossiers(id), counterparty_id uuid NOT NULL REFERENCES counterparties(id), home_jurisdiction text NOT NULL CHECK (length(home_jurisdiction) >= 2), exposure_tier text NOT NULL CHECK (exposure_tier IN ('standard','heightened','prohibited_review')), operating_summary text NOT NULL CHECK (length(operating_summary) >= 50), recorded_by text NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now(), UNIQUE(dossier_id,counterparty_id)
);
CREATE TABLE vasp_offshore_counterparty_evidence_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES vasp_offshore_counterparty_profiles(id), category text NOT NULL CHECK (category IN ('jurisdictional_authorisation_scope','ownership_and_control','sanctions_and_adverse_media_process','travel_rule_interoperability','data_protection_and_retention','incident_and_exit_contact')), evidence_uri text NOT NULL CHECK (evidence_uri ~ '^https://'), evidence_sha256 char(64) NOT NULL CHECK (evidence_sha256 ~ '^[a-f0-9]{64}$'), recorded_by text NOT NULL, recorded_at timestamptz NOT NULL DEFAULT now(), UNIQUE(profile_id,category,evidence_sha256)
);
CREATE TABLE vasp_offshore_counterparty_assessments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), profile_id uuid NOT NULL REFERENCES vasp_offshore_counterparty_profiles(id), required_categories jsonb NOT NULL, recorded_categories jsonb NOT NULL, missing_categories jsonb NOT NULL, outcome text NOT NULL CHECK (outcome IN ('internal_record_incomplete','internal_record_complete_pending_external_review')), reviewer_rationale text NOT NULL CHECK (length(reviewer_rationale) >= 20), assessed_by text NOT NULL, assessed_at timestamptz NOT NULL DEFAULT now(), external_counterparty_verification boolean NOT NULL DEFAULT false CHECK (external_counterparty_verification = false), provider_activation boolean NOT NULL DEFAULT false CHECK (provider_activation = false), custody_authority boolean NOT NULL DEFAULT false CHECK (custody_authority = false), value_movement boolean NOT NULL DEFAULT false CHECK (value_movement = false)
);
