{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "umoja-retention-worker.serviceAccountName" . }}
  labels:
    {{- include "umoja-retention-worker.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "umoja-retention-worker.fullname" . }}
  labels:
    {{- include "umoja-retention-worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "umoja-retention-worker.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
