port 0
tls-port 6379
tls-cert-file /run/secrets/redis/tls.crt
tls-key-file /run/secrets/redis/tls.key
tls-ca-cert-file /run/secrets/redis/ca.crt
tls-auth-clients yes
protected-mode yes
bind 0.0.0.0
requirepass ${REDIS_PASSWORD}
appendonly yes
appendfsync everysec
save ""
rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command SHUTDOWN ""
