import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { RateLockForm, RateLockTable } from "@/components/RateLockControls";
import { PaymentLegForm, PaymentLegTable } from "@/components/PaymentLegControls";
import { RegulatoryDeadlineForm, RegulatoryDeadlineTable } from "@/components/RegulatoryDeadlineControls";
import { CounterpartyAuthorizationForm, CounterpartyAuthorizationTable } from "@/components/CounterpartyAuthorizationControls";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { canPerformConsoleAction, type ConsoleAction } from "@/lib/roleCapabilities";
import { AlertTriangle, ArrowUpRight, CircleAlert, DatabaseZap, FileCheck2, Plus, ShieldAlert } from "lucide-react";
import { FormEvent, ReactNode, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type ModuleKey = "overview" | "payments" | "treasury" | "markets" | "compliance" | "reports" | "registry" | "integrations" | "governance" | "alerts";

const moduleMeta: Record<ModuleKey, { number: string; title: string; subtitle: string }> = {
  overview: { number: "00", title: "Operating posture", subtitle: "A source-honest view of configured control-plane records across Nigeria (NGN), Kenya (KES), and South Africa (ZAR)." },
  payments: { number: "01", title: "Payment orchestration", subtitle: "Draft and inspect cross-border payment orders. Execution remains blocked until a verified policy decision and provider finality exist." },
  treasury: { number: "02", title: "Treasury & liquidity", subtitle: "Record reconciled liquidity, nostro, vostro, pre-funding, and custody positions with attributable source evidence." },
  markets: { number: "03", title: "FX & stablecoin evidence", subtitle: "Ingest only source-stamped NGN, KES, ZAR, USDC, and USDT observations from verified active integrations." },
  compliance: { number: "04", title: "Compliance operations", subtitle: "Track KYC, sanctions, transaction-monitoring, Travel Rule, counterparty, and SAR/STR cases with clear disposition evidence." },
  reports: { number: "05", title: "CBN · CBK · SARB reporting", subtitle: "Create reviewed report packs. Submission status is never represented as complete without a verified submission channel and reference." },
  registry: { number: "06", title: "Counterparty registry", subtitle: "Record regulated payment, banking, stablecoin, FX, custody, KYC, screening, and reporting counterparties with evidence." },
  integrations: { number: "07", title: "Integration control", subtitle: "Register documented provider connections. Activation is reserved for verified secret-backed health checks, not a manual dashboard toggle." },
  governance: { number: "08", title: "Corridor governance", subtitle: "Version explicit Nigeria (NGN), Kenya (KES), and South Africa (ZAR) policy controls for CBN, CBK, and SARB review." },
  alerts: { number: "09", title: "Alert policy", subtitle: "Define owner-facing threshold, payment failure, compliance flag, and regulatory deadline alert policies without asserting delivery before the relevant channel is active." },
};

function moduleFromPath(path: string): ModuleKey {
  const part = path.split("/")[1] as ModuleKey;
  return part && part in moduleMeta ? part : "overview";
}

function cleanCount(value: unknown) {
  return String(value ?? "0");
}

function StatusBadge({ value }: { value: string | null | undefined }) {
  const normalized = value?.replaceAll("_", " ") ?? "unavailable";
  const tone = /active|verified|clear|completed|submitted|closed|allow/.test(normalized) ? "bg-black text-white" : /failed|blocked|critical|rejected|suspended/.test(normalized) ? "bg-[#e11919] text-white" : "bg-black/5 text-black";
  return <Badge className={`${tone} rounded-none border-0 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide`}>{normalized}</Badge>;
}

function Panel({ eyebrow, title, action, children }: { eyebrow: string; title: string; action?: ReactNode; children: ReactNode }) {
  return <section className="uf-panel min-w-0">
    <div className="flex items-start justify-between gap-4 border-b border-black/20 px-5 py-4">
      <div><p className="uf-kicker">{eyebrow}</p><h2 className="mt-1 text-lg font-black tracking-[-0.045em] uppercase">{title}</h2></div>
      {action}
    </div>
    {children}
  </section>;
}

function Empty({ title, detail }: { title: string; detail: string }) {
  return <div className="px-5 py-10"><p className="text-base font-bold">{title}</p><p className="mt-2 max-w-xl text-sm leading-6 text-black/55">{detail}</p></div>;
}

function TableShell({ children }: { children: ReactNode }) { return <div className="overflow-x-auto">{children}</div>; }

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-black/50">{label}</span>{children}</label>; }

function CorridorSelect({ value, onValueChange }: { value: string; onValueChange: (value: string) => void }) {
  return <Select value={value} onValueChange={onValueChange}><SelectTrigger className="rounded-none border-black/25"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="NIGERIA_NGN">Nigeria (NGN)</SelectItem><SelectItem value="KENYA_KES">Kenya (KES)</SelectItem><SelectItem value="SOUTH_AFRICA_ZAR">South Africa (ZAR)</SelectItem></SelectContent></Select>;
}

export default function Home() {
  const { user } = useAuth();
  const [location] = useLocation();
  const module = moduleFromPath(location);
  const meta = moduleMeta[module];
  const utils = trpc.useUtils();
  const overview = trpc.umoja.overview.useQuery();
  const postgresCutover = trpc.postgres.cutoverReadiness.useQuery();
  const postgresLiquidity = trpc.postgres.liquidityPositions.useQuery();
  const postgresReports = trpc.postgres.regulatoryReports.useQuery();
  const postgresVerificationConsents = trpc.postgres.verificationConsents.useQuery();
  const counterparties = trpc.umoja.registry.list.useQuery();
  const counterpartyAuthorizations = trpc.umoja.registry.listAuthorizations.useQuery();
  const integrations = trpc.umoja.integrations.list.useQuery();
  const policies = trpc.umoja.policies.list.useQuery();
  const customers = trpc.umoja.parties.listCustomers.useQuery();
  const beneficiaries = trpc.umoja.parties.listBeneficiaries.useQuery();
  const liquidity = trpc.umoja.treasury.listLiquidity.useQuery();
  const markets = trpc.umoja.markets.list.useQuery();
  const rateLocks = trpc.umoja.markets.listRateLocks.useQuery();
  const payments = trpc.umoja.payments.list.useQuery();
  const paymentLegs = trpc.umoja.payments.listLegs.useQuery();
  const cases = trpc.umoja.compliance.list.useQuery();
  const reports = trpc.umoja.reporting.list.useQuery();
  const deadlines = trpc.umoja.reporting.listDeadlines.useQuery();
  const alerts = trpc.umoja.alerts.list.useQuery();
  const [composer, setComposer] = useState<string | null>(null);
  const canAdmin = user?.role === "admin";

  const refresh = async () => { await Promise.all([utils.umoja.overview.invalidate(), utils.umoja.registry.list.invalidate(), utils.umoja.registry.listAuthorizations.invalidate(), utils.umoja.integrations.list.invalidate(), utils.umoja.policies.list.invalidate(), utils.umoja.parties.listCustomers.invalidate(), utils.umoja.parties.listBeneficiaries.invalidate(), utils.postgres.liquidityPositions.invalidate(), utils.postgres.regulatoryReports.invalidate(), utils.postgres.verificationConsents.invalidate(), utils.umoja.markets.list.invalidate(), utils.umoja.markets.listRateLocks.invalidate(), utils.umoja.payments.list.invalidate(), utils.umoja.payments.listLegs.invalidate(), utils.umoja.compliance.list.invalidate(), utils.umoja.reporting.list.invalidate(), utils.umoja.reporting.listDeadlines.invalidate(), utils.umoja.alerts.list.invalidate()]); };
  const onSuccess = async (message: string) => { toast.success(message); setComposer(null); await refresh(); };

  const createCounterparty = trpc.umoja.registry.create.useMutation({ onSuccess: () => onSuccess("Counterparty record created"), onError: error => toast.error(error.message) });
  const createCounterpartyAuthorization = trpc.umoja.registry.createAuthorization.useMutation({ onSuccess: () => onSuccess("Counterparty licence evidence recorded"), onError: error => toast.error(error.message) });
  const transitionCounterpartyAuthorization = trpc.umoja.registry.transitionAuthorization.useMutation({ onSuccess: () => onSuccess("Counterparty licence lifecycle updated"), onError: error => toast.error(error.message) });
  const createIntegration = trpc.umoja.integrations.create.useMutation({ onSuccess: () => onSuccess("Integration connection recorded in an unconfigured state"), onError: error => toast.error(error.message) });
  const createPolicy = trpc.umoja.policies.create.useMutation({ onSuccess: () => onSuccess("Corridor policy version created"), onError: error => toast.error(error.message) });
  const createCustomer = trpc.umoja.parties.createCustomer.useMutation({ onSuccess: () => onSuccess("Customer record created"), onError: error => toast.error(error.message) });
  const createBeneficiary = trpc.umoja.parties.createBeneficiary.useMutation({ onSuccess: () => onSuccess("Beneficiary record created"), onError: error => toast.error(error.message) });
  const recordLiquidity = trpc.postgres.recordLiquidityPosition.useMutation({ onSuccess: () => onSuccess("Canonical PostgreSQL liquidity evidence recorded"), onError: error => toast.error(error.message) });
  const recordMarket = trpc.umoja.markets.record.useMutation({ onSuccess: () => onSuccess("Market observation recorded"), onError: error => toast.error(error.message) });
  const createRateLock = trpc.umoja.markets.createRateLock.useMutation({ onSuccess: () => onSuccess("Rate lock created from the selected source observation"), onError: error => toast.error(error.message) });
  const createPayment = trpc.umoja.payments.create.useMutation({ onSuccess: () => onSuccess("Payment order drafted for policy evaluation"), onError: error => toast.error(error.message) });
  const createPaymentLeg = trpc.umoja.payments.createLeg.useMutation({ onSuccess: () => onSuccess("Payment leg created in draft state"), onError: error => toast.error(error.message) });
  const createCase = trpc.umoja.compliance.create.useMutation({ onSuccess: () => onSuccess("Compliance case created"), onError: error => toast.error(error.message) });
  const createReport = trpc.umoja.reporting.create.useMutation({ onSuccess: () => onSuccess("Regulatory report pack created as draft"), onError: error => toast.error(error.message) });
  const createDeadline = trpc.umoja.reporting.createDeadline.useMutation({ onSuccess: () => onSuccess("Regulatory deadline recorded"), onError: error => toast.error(error.message) });
  const createAlert = trpc.umoja.alerts.create.useMutation({ onSuccess: () => onSuccess("Alert policy created"), onError: error => toast.error(error.message) });
  const evaluateDeadlines = trpc.umoja.alerts.evaluateDeadlines.useMutation({ onSuccess: result => toast.success(`Evaluated ${result.evaluated} deadlines; ${result.reminded} reminder(s) issued`), onError: error => toast.error(error.message) });

  const counts = useMemo(() => ({ counterparty: overview.data?.counterpartyCounts.reduce((sum, row) => sum + Number(row.count), 0) ?? 0, integration: overview.data?.integrationCounts.reduce((sum, row) => sum + Number(row.count), 0) ?? 0, payment: overview.data?.paymentCounts.reduce((sum, row) => sum + Number(row.count), 0) ?? 0, case: overview.data?.caseCounts.reduce((sum, row) => sum + Number(row.count), 0) ?? 0 }), [overview.data]);

  const actionAllowed = (kind: string) => kind === "authorization" ? canAdmin : canPerformConsoleAction(user?.role, kind as ConsoleAction);
  const openComposer = (kind: string) => {
    if (!actionAllowed(kind)) {
      toast.error("Your assigned role does not permit this operational action.");
      return;
    }
    setComposer(kind);
  };
  const button = (label: string, kind: string) => actionAllowed(kind) ? <Button onClick={() => openComposer(kind)} className="rounded-none bg-[#e11919] px-3 text-xs font-black uppercase tracking-wide text-white hover:bg-black"><Plus className="mr-1.5 h-3.5 w-3.5" />{label}</Button> : null;

  return <DashboardLayout><div className="min-h-full">
    <header className="border-b border-black/20 bg-white px-5 py-4 sm:px-8">
      <div className="mx-auto flex max-w-[1600px] items-end justify-between gap-6"><div className="flex items-end gap-4"><span className="flex h-12 w-12 items-center justify-center bg-[#e11919] text-2xl font-black text-white">{meta.number}</span><div><p className="uf-kicker">UmojaFlowOS / Africa-linked cross-border payments</p><h1 className="uf-title text-3xl sm:text-4xl">{meta.title}</h1></div></div><div className="hidden text-right md:block"><p className="uf-kicker">System claim status</p><p className="mt-1 text-sm font-bold">Source-honest / provider-gated</p></div></div>
    </header>
    <main className="mx-auto max-w-[1600px] px-5 py-6 sm:px-8"><p className="mb-6 max-w-4xl text-sm leading-6 text-black/65">{meta.subtitle}</p>
      {module === "overview" && <div className="grid gap-5 xl:grid-cols-[1.25fr_0.75fr]">
        <div className="grid gap-5 sm:grid-cols-2"><Metric title="Registered counterparties" value={counts.counterparty} detail="Actual registry records only" /><Metric title="Configured integrations" value={counts.integration} detail="Activation requires a verified health check" /><Metric title="Payment orders" value={counts.payment} detail="Final settlement evidence is distinct from draft state" /><Metric title="Compliance cases" value={counts.case} detail="Open, reviewed, escalated, reported, and closed cases" /></div>
        <Panel eyebrow="Activation guard" title="Live-capability boundary"><div className="space-y-0"><Guard title="PostgreSQL cutover" detail={postgresCutover.isLoading ? "Checking the local canonical PostgreSQL schema." : postgresCutover.data?.ready ? `Local PostgreSQL schema validated (${postgresCutover.data.presentTableCount} canonical tables). Production deployment and service cutover remain separate gates.` : `PostgreSQL cutover is blocked: ${postgresCutover.data?.missingTables.join(", ") ?? "readiness unavailable"}.`} /><Guard title="Payment execution" detail="Unavailable until an authorised, credential-verified provider is connected and a policy decision is recorded." /><Guard title="Market observations" detail="Accepted only from an active integration with source timestamps and references." /><Guard title="Regulatory submission" detail="Requires a verified official submission channel and submission reference." /></div></Panel>
        <Panel eyebrow="Audit trail" title="Latest attributable activity"><ActivityList events={overview.data?.latestEvents ?? []} loading={overview.isLoading} /></Panel>
      </div>}
      {module === "registry" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Counterparty and licence evidence" action={<div className="flex flex-wrap justify-end gap-2">{button("Record", "counterparty")}{button("Licence", "authorization")}</div>}>{composer === "counterparty" ? <CounterpartyForm pending={createCounterparty.isPending} submit={createCounterparty.mutate} /> : composer === "authorization" ? <CounterpartyAuthorizationForm pending={createCounterpartyAuthorization.isPending} counterparties={counterparties.data ?? []} submit={createCounterpartyAuthorization.mutate} /> : <Empty title="Licence evidence requires administrator access" detail="Administrators may register a licensed PSP, correspondent bank, stablecoin provider, FX liquidity provider, custody provider, KYC provider, sanctions provider, chain analytics provider, notification provider, or regulatory-submission provider and attach source-backed licence evidence." />}</Panel><div className="grid gap-5"><Panel eyebrow="Registry" title="Recorded counterparties"><CounterpartyTable rows={counterparties.data ?? []} loading={counterparties.isLoading} /></Panel><Panel eyebrow="Licence register" title="Counterparty authorisations"><CounterpartyAuthorizationTable rows={counterpartyAuthorizations.data ?? []} loading={counterpartyAuthorizations.isLoading} canManage={canAdmin} pending={transitionCounterpartyAuthorization.isPending} transition={(authorizationId, status) => transitionCounterpartyAuthorization.mutate({ authorizationId, status })} /></Panel></div></div>}
      {module === "integrations" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Document provider connection" action={button("New connection", "integration")}>{composer === "integration" ? <IntegrationForm pending={createIntegration.isPending} counterparties={counterparties.data ?? []} submit={createIntegration.mutate} /> : <Empty title="No live connection represented" detail="Provider credentials must be supplied through protected deployment configuration. Creating this record does not activate a payment rail, FX rate, stablecoin market-data feed, KYC/KYB, sanctions, chain-analysis, notification, or reporting integration." />}</Panel><Panel eyebrow="Control register" title="Connection state"><IntegrationTable rows={integrations.data ?? []} loading={integrations.isLoading} /></Panel></div>}
      {module === "governance" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Version corridor policy" action={button("New policy", "policy")}>{composer === "policy" ? <PolicyForm pending={createPolicy.isPending} submit={createPolicy.mutate} /> : <Empty title="Policy is a runtime gate" detail="A policy version must name the corridor, relevant regulator—CBN, CBK, or SARB—and source document. It is created pending review and cannot itself authorise a payment execution." />}</Panel><Panel eyebrow="Policy ledger" title="Corridor policy versions"><PolicyTable rows={policies.data ?? []} loading={policies.isLoading} /></Panel></div>}
      {module === "treasury" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Record reconciled position" action={button("New position", "liquidity")}>{composer === "liquidity" ? <LiquidityForm pending={recordLiquidity.isPending} submit={recordLiquidity.mutate} /> : <Empty title="No automatic balance is claimed" detail="Record a position only after reconciliation against its actual nostro, vostro, pre-funding, liquidity pool, or custody-wallet source reference." />}</Panel><Panel eyebrow="Evidence ledger" title="Canonical PostgreSQL liquidity positions"><LiquidityTable rows={postgresLiquidity.data ?? []} loading={postgresLiquidity.isLoading} /></Panel></div>}
      {module === "markets" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Rate evidence and lock" action={<div className="flex flex-wrap justify-end gap-2">{button("Observe", "market")}{button("Lock", "rate-lock")}</div>}>{composer === "market" ? <MarketForm pending={recordMarket.isPending} integrations={integrations.data ?? []} submit={recordMarket.mutate} /> : composer === "rate-lock" ? <RateLockForm pending={createRateLock.isPending} observations={markets.data ?? []} payments={payments.data ?? []} submit={createRateLock.mutate} /> : <Empty title="No FX or peg values are fabricated" detail="NGN, KES, ZAR, USDC, and USDT observations require a previously verified active integration. Rate locks are derived only from a persisted source observation and cannot be manually quoted." />}</Panel><div className="grid gap-5"><Panel eyebrow="Rate evidence" title="Latest observations"><MarketTable rows={markets.data ?? []} loading={markets.isLoading} /></Panel><Panel eyebrow="Lock ledger" title="Source-derived rate locks"><RateLockTable rows={rateLocks.data ?? []} loading={rateLocks.isLoading} /></Panel></div></div>}
      {module === "payments" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Controlled intake" title="Participants and payment workflow" action={<div className="flex flex-wrap justify-end gap-2">{button("Draft", "payment")}{button("Leg", "payment-leg")}</div>}>{composer === "customer" ? <CustomerForm pending={createCustomer.isPending} submit={createCustomer.mutate} /> : composer === "beneficiary" ? <BeneficiaryForm pending={createBeneficiary.isPending} customers={customers.data ?? []} submit={createBeneficiary.mutate} /> : composer === "payment" ? <PaymentForm pending={createPayment.isPending} customers={customers.data ?? []} beneficiaries={beneficiaries.data ?? []} submit={createPayment.mutate} /> : composer === "payment-leg" ? <PaymentLegForm pending={createPaymentLeg.isPending} payments={payments.data ?? []} counterparties={counterparties.data ?? []} submit={createPaymentLeg.mutate} /> : canPerformConsoleAction(user?.role, "payment") ? <div className="space-y-3 px-5 py-6"><p className="text-sm leading-6 text-black/65">A draft requires real customer and beneficiary records. Each payment leg remains a non-executing draft until policy, counterparty, and verified provider controls are satisfied.</p><div className="flex flex-wrap gap-2"><Button variant="outline" className="rounded-none border-black/25" onClick={() => openComposer("customer")}>1. Add customer</Button><Button variant="outline" className="rounded-none border-black/25" onClick={() => openComposer("beneficiary")}>2. Add beneficiary</Button><Button className="rounded-none bg-[#e11919] hover:bg-black" onClick={() => openComposer("payment")}>3. Draft payment</Button><Button variant="outline" className="rounded-none border-black/25" onClick={() => openComposer("payment-leg")}>4. Add leg</Button></div></div> : <Empty title="Read-only payment evidence" detail="Your assigned role may inspect payment orders and legs but cannot create or change payment workflow records." />}</Panel><div className="grid gap-5"><Panel eyebrow="Workflow" title="Payment orders"><PaymentTable rows={payments.data ?? []} loading={payments.isLoading} /></Panel><Panel eyebrow="Leg ledger" title="Payment legs"><PaymentLegTable rows={paymentLegs.data ?? []} loading={paymentLegs.isLoading} /></Panel></div></div>}
      {module === "compliance" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Open evidence-based case" action={button("New case", "case")}>{composer === "case" ? <ComplianceForm pending={createCase.isPending} submit={createCase.mutate} /> : <Empty title="Screening results are never invented" detail="Create a case from a verified source reference for KYC, sanctions, transaction monitoring, Travel Rule, counterparty, or SAR/STR workflow evidence. A potential match requires authorised review." />}</Panel><div className="grid gap-5"><Panel eyebrow="Casework" title="Compliance cases"><CaseTable rows={cases.data ?? []} loading={cases.isLoading} /></Panel><Panel eyebrow="KYC/KYB consent ledger" title="Canonical PostgreSQL consent evidence"><VerificationConsentTable rows={postgresVerificationConsents.data ?? []} loading={postgresVerificationConsents.isLoading} /></Panel></div></div>}
      {module === "reports" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Report pack and deadline" action={<div className="flex flex-wrap justify-end gap-2">{button("Report", "report")}{button("Deadline", "deadline")}</div>}>{composer === "report" ? <ReportForm pending={createReport.isPending} submit={createReport.mutate} /> : composer === "deadline" ? <RegulatoryDeadlineForm pending={createDeadline.isPending} submit={createDeadline.mutate} /> : <Empty title="Submission is not inferred" detail="Create an auditable CBN, CBK, or SARB report draft and source-backed deadline. A record cannot be called submitted until a verified regulatory channel returns an attributable submission reference." />}</Panel><div className="grid gap-5"><Panel eyebrow="Reporting register" title="Canonical PostgreSQL report packs"><PostgresReportTable rows={postgresReports.data ?? []} loading={postgresReports.isLoading} /></Panel><Panel eyebrow="Deadline register" title="CBN, CBK, and SARB deadlines"><RegulatoryDeadlineTable rows={deadlines.data ?? []} loading={deadlines.isLoading} /></Panel></div></div>}
      {module === "alerts" && <div className="grid gap-5 xl:grid-cols-[1fr_1.45fr]"><Panel eyebrow="Action" title="Define and evaluate policy" action={<div className="flex flex-wrap justify-end gap-2">{button("Policy", "alert")}{canAdmin && <Button disabled={evaluateDeadlines.isPending} className="rounded-none bg-black text-white hover:bg-[#e11919]" onClick={() => evaluateDeadlines.mutate()}>{evaluateDeadlines.isPending ? "Evaluating…" : "Evaluate"}</Button>}</div>}>{composer === "alert" ? <AlertForm pending={createAlert.isPending} submit={createAlert.mutate} /> : <Empty title="Alert policy is not delivery evidence" detail="Policies are stored with the configured threshold. An administrator may evaluate deadline records; scheduled evaluation becomes available only after deployment. Owner delivery is contingent on the relevant source event." />}</Panel><Panel eyebrow="Alert ledger" title="Configured policies"><AlertTable rows={alerts.data ?? []} loading={alerts.isLoading} /></Panel></div>}
    </main>
  </div></DashboardLayout>;
}

function Metric({ title, value, detail }: { title: string; value: number; detail: string }) { return <div className="uf-panel min-h-48 p-5"><p className="uf-kicker">{title}</p><p className="uf-metric mt-8 text-6xl">{value}</p><p className="mt-4 text-xs leading-5 text-black/55">{detail}</p></div>; }
function Guard({ title, detail }: { title: string; detail: string }) { return <div className="border-b border-black/15 px-5 py-4 last:border-b-0"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-4 w-4 text-[#e11919]" /><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-black/60">{detail}</p></div></div></div>; }
function ActivityList({ events, loading }: { events: Array<{ id: number; action: string; objectType: string; occurredAt: Date }>; loading: boolean }) { if (loading) return <Empty title="Loading activity" detail="Retrieving immutable control-plane activity records." />; if (!events.length) return <Empty title="No activity records yet" detail="Activity appears here only after a real operator action is performed through the platform." />; return <div className="divide-y divide-black/15">{events.map(event => <div className="flex items-start justify-between gap-4 px-5 py-3" key={event.id}><div><p className="text-sm font-bold">{event.action}</p><p className="mt-0.5 text-xs text-black/55">{event.objectType} / {new Date(event.occurredAt).toLocaleString()}</p></div><ArrowUpRight className="h-4 w-4 text-black/40" /></div>)}</div>; }
function DataLoading({ loading, empty, children }: { loading: boolean; empty: boolean; children: ReactNode }) { if (loading) return <Empty title="Loading verified records" detail="The platform is retrieving persisted operational records." />; if (empty) return <Empty title="No records exist" detail="No data is shown until an authorised operator creates or ingests a traceable record." />; return <>{children}</>; }
function CounterpartyTable({ rows, loading }: { rows: Array<{ id: number; legalName: string; counterpartyType: string; jurisdiction: string; updatedAt: Date }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Legal entity</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Jurisdiction</th><th className="px-4 py-3">Updated</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.legalName}</td><td className="px-4 py-3"><StatusBadge value={row.counterpartyType} /></td><td className="px-4 py-3">{row.jurisdiction}</td><td className="px-4 py-3 text-black/55">{new Date(row.updatedAt).toLocaleString()}</td></tr>)}</tbody></table></TableShell></DataLoading>; }
function IntegrationTable({ rows, loading }: { rows: Array<{ integration: { id: number; category: string; environment: string; state: string; documentationUrl: string }; counterpartyName: string }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Counterparty</th><th className="px-4 py-3">Capability</th><th className="px-4 py-3">Environment</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.integration.id}><td className="px-5 py-3 font-bold">{row.counterpartyName}</td><td className="px-4 py-3">{row.integration.category.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.integration.environment}</td><td className="px-4 py-3"><StatusBadge value={row.integration.state} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function PolicyTable({ rows, loading }: { rows: Array<{ id: number; corridor: string; regulator: string; policyVersion: string; activationStatus: string; requiresTravelRule: boolean }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Corridor</th><th className="px-4 py-3">Regulator</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Travel Rule</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.corridor.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.regulator}</td><td className="px-4 py-3">{row.policyVersion}</td><td className="px-4 py-3">{row.requiresTravelRule ? "Required" : "Not configured"}</td><td className="px-4 py-3"><StatusBadge value={row.activationStatus} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function LiquidityTable({ rows, loading }: { rows: Array<{ id: string; corridor: string; currency: string; accountKind: string; availableAmount: string; reservedAmount: string; reconciledAt: Date }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Corridor</th><th className="px-4 py-3">Account</th><th className="px-4 py-3">Available</th><th className="px-4 py-3">Reserved</th><th className="px-4 py-3">Reconciled</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.corridor.replaceAll("_", " ")} / {row.currency}</td><td className="px-4 py-3">{row.accountKind.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.availableAmount}</td><td className="px-4 py-3">{row.reservedAmount}</td><td className="px-4 py-3">{new Date(row.reconciledAt).toLocaleString()}</td></tr>)}</tbody></table></TableShell></DataLoading>; }
function MarketTable({ rows, loading }: { rows: Array<{ id: number; baseAsset: string; quoteAsset: string; rate: string; observedAt: Date; sourceReference: string }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Pair</th><th className="px-4 py-3">Rate</th><th className="px-4 py-3">Observed</th><th className="px-4 py-3">Evidence</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.baseAsset} / {row.quoteAsset}</td><td className="px-4 py-3">{row.rate}</td><td className="px-4 py-3">{new Date(row.observedAt).toLocaleString()}</td><td className="px-4 py-3"><a className="underline decoration-black/30 underline-offset-4" href={row.sourceReference} target="_blank" rel="noreferrer">Source</a></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function PaymentTable({ rows, loading }: { rows: Array<{ id: number; corridor: string; sourceCurrency: string; sourceAmount: string; targetCurrency: string; targetAmount: string | null; status: string; createdAt: Date }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Order</th><th className="px-4 py-3">Corridor</th><th className="px-4 py-3">Source</th><th className="px-4 py-3">Target</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">#{row.id}</td><td className="px-4 py-3">{row.corridor.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.sourceAmount} {row.sourceCurrency}</td><td className="px-4 py-3">{row.targetAmount ?? "—"} {row.targetCurrency}</td><td className="px-4 py-3"><StatusBadge value={row.status} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function CaseTable({ rows, loading }: { rows: Array<{ id: number; caseType: string; status: string; severity: string; openedAt: Date; sourceReference: string }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Case</th><th className="px-4 py-3">Severity</th><th className="px-4 py-3">State</th><th className="px-4 py-3">Opened</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.caseType.replaceAll("_", " ")}</td><td className="px-4 py-3"><StatusBadge value={row.severity} /></td><td className="px-4 py-3"><StatusBadge value={row.status} /></td><td className="px-4 py-3">{new Date(row.openedAt).toLocaleString()}</td></tr>)}</tbody></table></TableShell></DataLoading>; }
function VerificationConsentTable({ rows, loading }: { rows: Array<{ id: string; scope: string; subjectReference: string; consentVersion: string; purpose: string; grantedAt: Date; expiresAt: Date | null; capturedBy: string }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Scope</th><th className="px-4 py-3">Purpose</th><th className="px-4 py-3">Version</th><th className="px-4 py-3">Granted</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.scope.toUpperCase()}</td><td className="px-4 py-3">{row.purpose}</td><td className="px-4 py-3">{row.consentVersion}</td><td className="px-4 py-3">{new Date(row.grantedAt).toLocaleString()}</td></tr>)}</tbody></table></TableShell></DataLoading>; }
function ReportTable({ rows, loading }: { rows: Array<{ id: number; regulator: string; corridor: string; reportType: string; periodEnd: Date; status: string }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Regulator</th><th className="px-4 py-3">Corridor</th><th className="px-4 py-3">Report</th><th className="px-4 py-3">Period end</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.regulator}</td><td className="px-4 py-3">{row.corridor.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.reportType}</td><td className="px-4 py-3">{new Date(row.periodEnd).toLocaleDateString()}</td><td className="px-4 py-3"><StatusBadge value={row.status} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function PostgresReportTable({ rows, loading }: { rows: Array<{ id: string; regulator: string; corridor: string; reportType: string; periodEnd: Date; status: string; artifactUri: string | null; submissionReference: string | null }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Regulator</th><th className="px-4 py-3">Corridor</th><th className="px-4 py-3">Report</th><th className="px-4 py-3">Period end</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.regulator}</td><td className="px-4 py-3">{row.corridor.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.reportType}</td><td className="px-4 py-3">{new Date(row.periodEnd).toLocaleDateString()}</td><td className="px-4 py-3"><StatusBadge value={row.status} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }
function AlertTable({ rows, loading }: { rows: Array<{ id: number; alertType: string; corridor: string | null; enabled: boolean; threshold: unknown }>; loading: boolean }) { return <DataLoading loading={loading} empty={!rows.length}><TableShell><table className="w-full text-left text-xs"><thead className="border-b border-black/20 text-[10px] uppercase tracking-wider text-black/45"><tr><th className="px-5 py-3">Trigger</th><th className="px-4 py-3">Corridor</th><th className="px-4 py-3">Threshold</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row => <tr className="border-b border-black/10" key={row.id}><td className="px-5 py-3 font-bold">{row.alertType.replaceAll("_", " ")}</td><td className="px-4 py-3">{row.corridor?.replaceAll("_", " ") ?? "All corridors"}</td><td className="max-w-48 truncate px-4 py-3">{JSON.stringify(row.threshold)}</td><td className="px-4 py-3"><StatusBadge value={row.enabled ? "enabled" : "disabled"} /></td></tr>)}</tbody></table></TableShell></DataLoading>; }

function FormShell({ onSubmit, children, pending }: { onSubmit: (event: FormEvent<HTMLFormElement>) => void; children: ReactNode; pending: boolean }) { return <form className="grid gap-4 p-5" onSubmit={onSubmit}>{children}<Button disabled={pending} type="submit" className="rounded-none bg-[#e11919] font-black uppercase tracking-wide hover:bg-black">{pending ? "Saving…" : "Save attributable record"}</Button></form>; }
function CounterpartyForm({ submit, pending }: { submit: (input: { legalName: string; counterpartyType: "licensed_psp" | "correspondent_bank" | "stablecoin_provider" | "fx_liquidity_provider" | "custody_provider" | "kyc_provider" | "sanctions_provider" | "chain_analytics_provider" | "notification_provider" | "regulatory_submission_provider"; jurisdiction: string }) => void; pending: boolean }) { const [kind, setKind] = useState<"licensed_psp" | "correspondent_bank" | "stablecoin_provider" | "fx_liquidity_provider" | "custody_provider" | "kyc_provider" | "sanctions_provider" | "chain_analytics_provider" | "notification_provider" | "regulatory_submission_provider">("licensed_psp"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); submit({ legalName: String(data.get("legalName")), counterpartyType: kind, jurisdiction: String(data.get("jurisdiction")) }); }}><Field label="Legal name"><Input name="legalName" required className="rounded-none" /></Field><Field label="Type"><Select value={kind} onValueChange={value => setKind(value as typeof kind)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["licensed_psp", "correspondent_bank", "stablecoin_provider", "fx_liquidity_provider", "custody_provider", "kyc_provider", "sanctions_provider", "chain_analytics_provider", "notification_provider", "regulatory_submission_provider"].map(value => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Jurisdiction"><Input name="jurisdiction" required placeholder="Nigeria, Kenya, South Africa, or provider jurisdiction" className="rounded-none" /></Field></FormShell>; }
function IntegrationForm({ counterparties, submit, pending }: { counterparties: Array<{ id: number; legalName: string }>; submit: (input: { counterpartyId: number; category: "payment_rail" | "fx_rate" | "stablecoin_market_data" | "kyc_kyb" | "sanctions" | "chain_analytics" | "notification" | "regulatory_submission"; environment: "sandbox" | "production"; documentationUrl: string; secretReference?: string }) => void; pending: boolean }) { const [category, setCategory] = useState<"payment_rail" | "fx_rate" | "stablecoin_market_data" | "kyc_kyb" | "sanctions" | "chain_analytics" | "notification" | "regulatory_submission">("payment_rail"); const [environment, setEnvironment] = useState<"sandbox" | "production">("sandbox"); if (!counterparties.length) return <Empty title="Counterparty required" detail="Create the legal counterparty record before documenting an integration connection." />; return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); submit({ counterpartyId: Number(data.get("counterpartyId")), category, environment, documentationUrl: String(data.get("documentationUrl")), secretReference: String(data.get("secretReference")) || undefined }); }}><Field label="Counterparty"><Select name="counterpartyId" defaultValue={String(counterparties[0].id)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{counterparties.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.legalName}</SelectItem>)}</SelectContent></Select></Field><Field label="Capability"><Select value={category} onValueChange={value => setCategory(value as typeof category)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["payment_rail", "fx_rate", "stablecoin_market_data", "kyc_kyb", "sanctions", "chain_analytics", "notification", "regulatory_submission"].map(value => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Environment"><Select value={environment} onValueChange={value => setEnvironment(value as typeof environment)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="sandbox">Sandbox</SelectItem><SelectItem value="production">Production</SelectItem></SelectContent></Select></Field><Field label="Official documentation URL"><Input name="documentationUrl" required type="url" className="rounded-none" /></Field><Field label="Secret reference (optional, not secret value)"><Input name="secretReference" placeholder="e.g. provider_api_key" className="rounded-none" /></Field></FormShell>; }
function PolicyForm({ submit, pending }: { submit: (input: { corridor: "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR"; regulator: "CBN" | "CBK" | "SARB"; policyVersion: string; effectiveFrom: Date; effectiveTo?: Date; requiresTravelRule: boolean; requiresAuthorizedFxIntermediary: boolean; activationStatus: "pending_review" | "verified" | "expired" | "suspended" | "rejected"; policyDocumentUrl: string }) => void; pending: boolean }) { const [corridor, setCorridor] = useState("NIGERIA_NGN"); const [regulator, setRegulator] = useState<"CBN" | "CBK" | "SARB">("CBN"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ corridor: corridor as "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR", regulator, policyVersion: String(d.get("policyVersion")), effectiveFrom: new Date(String(d.get("effectiveFrom"))), requiresTravelRule: d.get("requiresTravelRule") === "on", requiresAuthorizedFxIntermediary: d.get("requiresAuthorizedFxIntermediary") === "on", activationStatus: "pending_review", policyDocumentUrl: String(d.get("policyDocumentUrl")) }); }}><Field label="Corridor"><CorridorSelect value={corridor} onValueChange={setCorridor} /></Field><Field label="Regulator"><Select value={regulator} onValueChange={value => setRegulator(value as typeof regulator)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="CBN">CBN</SelectItem><SelectItem value="CBK">CBK</SelectItem><SelectItem value="SARB">SARB</SelectItem></SelectContent></Select></Field><Field label="Policy version"><Input name="policyVersion" required placeholder="YYYY.MM.DD" className="rounded-none" /></Field><Field label="Effective from"><Input name="effectiveFrom" required type="date" className="rounded-none" /></Field><Field label="Primary policy source URL"><Input name="policyDocumentUrl" required type="url" className="rounded-none" /></Field><label className="flex gap-2 text-xs"><input name="requiresTravelRule" type="checkbox" /> Require Travel Rule data</label><label className="flex gap-2 text-xs"><input name="requiresAuthorizedFxIntermediary" type="checkbox" defaultChecked /> Require authorised FX intermediary</label></FormShell>; }
function CustomerForm({ submit, pending }: { submit: (input: { legalName: string; registrationIdentifier: string }) => void; pending: boolean }) { return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ legalName: String(d.get("legalName")), registrationIdentifier: String(d.get("registrationIdentifier")) }); }}><Field label="Legal name"><Input name="legalName" required className="rounded-none" /></Field><Field label="Registration identifier"><Input name="registrationIdentifier" required className="rounded-none" /></Field></FormShell>; }
function BeneficiaryForm({ customers, submit, pending }: { customers: Array<{ id: number; legalName: string }>; submit: (input: { customerId: number; legalName: string; countryCode: string; bankOrWalletReference: string }) => void; pending: boolean }) { if (!customers.length) return <Empty title="Customer required" detail="Create the customer before capturing a beneficiary." />; return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ customerId: Number(d.get("customerId")), legalName: String(d.get("legalName")), countryCode: String(d.get("countryCode")).toUpperCase(), bankOrWalletReference: String(d.get("bankOrWalletReference")) }); }}><Field label="Customer"><Select name="customerId" defaultValue={String(customers[0].id)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{customers.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.legalName}</SelectItem>)}</SelectContent></Select></Field><Field label="Beneficiary legal name"><Input name="legalName" required className="rounded-none" /></Field><Field label="Country code"><Input name="countryCode" required maxLength={2} placeholder="NG, KE, ZA" className="rounded-none" /></Field><Field label="Bank or wallet reference"><Input name="bankOrWalletReference" required className="rounded-none" /></Field></FormShell>; }
function LiquidityForm({ submit, pending }: { submit: (input: { corridor: "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR"; currency: "NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT"; accountKind: "liquidity_pool" | "nostro" | "vostro" | "prefunding" | "custody_wallet"; accountReference: string; availableAmount: string; reservedAmount: string; sourceReference: string; reconciledAt: Date }) => void; pending: boolean }) { const [corridor, setCorridor] = useState("NIGERIA_NGN"); const [currency, setCurrency] = useState<"NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT">("NGN"); const [accountKind, setAccountKind] = useState<"liquidity_pool" | "nostro" | "vostro" | "prefunding" | "custody_wallet">("liquidity_pool"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ corridor: corridor as "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR", currency, accountKind, accountReference: String(d.get("accountReference")), availableAmount: String(d.get("availableAmount")), reservedAmount: String(d.get("reservedAmount") || "0"), sourceReference: String(d.get("sourceReference")), reconciledAt: new Date(String(d.get("reconciledAt"))) }); }}><Field label="Corridor"><CorridorSelect value={corridor} onValueChange={setCorridor} /></Field><Field label="Currency"><Select value={currency} onValueChange={value => setCurrency(value as typeof currency)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["NGN", "KES", "ZAR", "USD", "USDC", "USDT"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Account kind"><Select value={accountKind} onValueChange={value => setAccountKind(value as typeof accountKind)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["liquidity_pool", "nostro", "vostro", "prefunding", "custody_wallet"].map(value => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Account reference"><Input name="accountReference" required className="rounded-none" /></Field><Field label="Available amount"><Input name="availableAmount" required inputMode="decimal" className="rounded-none" /></Field><Field label="Reserved amount"><Input name="reservedAmount" inputMode="decimal" defaultValue="0" className="rounded-none" /></Field><Field label="Reconciliation source reference"><Input name="sourceReference" required className="rounded-none" /></Field><Field label="Reconciled at"><Input name="reconciledAt" required type="datetime-local" className="rounded-none" /></Field></FormShell>; }
function MarketForm({ integrations, submit, pending }: { integrations: Array<{ integration: { id: number; state: string; category: string }; counterpartyName: string }>; submit: (input: { integrationConnectionId: number; baseAsset: "NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT"; quoteAsset: "NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT"; rate: string; observedAt: Date; sourceReference: string }) => void; pending: boolean }) { const active = integrations.filter(item => item.integration.state === "active" && ["fx_rate", "stablecoin_market_data"].includes(item.integration.category)); const [baseAsset, setBaseAsset] = useState<"NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT">("NGN"); const [quoteAsset, setQuoteAsset] = useState<"NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT">("USD"); if (!active.length) return <Empty title="Verified market-data connection required" detail="No active FX-rate or stablecoin-market-data integration exists. The system will not accept a manually asserted rate or USDC/USDT peg observation." />; return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ integrationConnectionId: Number(d.get("integrationConnectionId")), baseAsset, quoteAsset, rate: String(d.get("rate")), observedAt: new Date(String(d.get("observedAt"))), sourceReference: String(d.get("sourceReference")) }); }}><Field label="Verified integration"><Select name="integrationConnectionId" defaultValue={String(active[0].integration.id)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{active.map(item => <SelectItem key={item.integration.id} value={String(item.integration.id)}>{item.counterpartyName} / {item.integration.category}</SelectItem>)}</SelectContent></Select></Field><Field label="Base asset"><AssetSelect value={baseAsset} onValueChange={value => setBaseAsset(value as typeof baseAsset)} /></Field><Field label="Quote asset"><AssetSelect value={quoteAsset} onValueChange={value => setQuoteAsset(value as typeof quoteAsset)} /></Field><Field label="Observed rate"><Input name="rate" required inputMode="decimal" className="rounded-none" /></Field><Field label="Observed at"><Input name="observedAt" required type="datetime-local" className="rounded-none" /></Field><Field label="Source reference URL"><Input name="sourceReference" required type="url" className="rounded-none" /></Field></FormShell>; }
function AssetSelect({ value, onValueChange }: { value: string; onValueChange: (value: string) => void }) { return <Select value={value} onValueChange={onValueChange}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["NGN", "KES", "ZAR", "USD", "USDC", "USDT"].map(asset => <SelectItem key={asset} value={asset}>{asset}</SelectItem>)}</SelectContent></Select>; }
function PaymentForm({ customers, beneficiaries, submit, pending }: { customers: Array<{ id: number; legalName: string }>; beneficiaries: Array<{ id: number; legalName: string }>; submit: (input: { idempotencyKey: string; customerId: number; beneficiaryId: number; corridor: "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR"; sourceCurrency: "NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT"; sourceAmount: string; targetCurrency: "NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT"; targetAmount?: string }) => void; pending: boolean }) { const [corridor, setCorridor] = useState("NIGERIA_NGN"); const [sourceCurrency, setSourceCurrency] = useState<"NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT">("NGN"); const [targetCurrency, setTargetCurrency] = useState<"NGN" | "KES" | "ZAR" | "USD" | "USDC" | "USDT">("USD"); if (!customers.length || !beneficiaries.length) return <Empty title="Customer and beneficiary required" detail="Create real customer and beneficiary records before drafting a payment order." />; return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ idempotencyKey: crypto.randomUUID(), customerId: Number(d.get("customerId")), beneficiaryId: Number(d.get("beneficiaryId")), corridor: corridor as "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR", sourceCurrency, sourceAmount: String(d.get("sourceAmount")), targetCurrency, targetAmount: String(d.get("targetAmount")) || undefined }); }}><Field label="Customer"><Select name="customerId" defaultValue={String(customers[0].id)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{customers.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.legalName}</SelectItem>)}</SelectContent></Select></Field><Field label="Beneficiary"><Select name="beneficiaryId" defaultValue={String(beneficiaries[0].id)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{beneficiaries.map(item => <SelectItem key={item.id} value={String(item.id)}>{item.legalName}</SelectItem>)}</SelectContent></Select></Field><Field label="Corridor"><CorridorSelect value={corridor} onValueChange={setCorridor} /></Field><Field label="Source currency"><AssetSelect value={sourceCurrency} onValueChange={value => setSourceCurrency(value as typeof sourceCurrency)} /></Field><Field label="Source amount"><Input name="sourceAmount" required inputMode="decimal" className="rounded-none" /></Field><Field label="Target currency"><AssetSelect value={targetCurrency} onValueChange={value => setTargetCurrency(value as typeof targetCurrency)} /></Field><Field label="Target amount (if known)"><Input name="targetAmount" inputMode="decimal" className="rounded-none" /></Field></FormShell>; }
function ComplianceForm({ submit, pending }: { submit: (input: { caseType: "kyc" | "sanctions" | "transaction_monitoring" | "travel_rule" | "counterparty" | "sar_str"; status: "open" | "under_review" | "cleared" | "escalated" | "reported" | "closed"; severity: "low" | "medium" | "high" | "critical"; sourceReference: string; decisionReason?: string }) => void; pending: boolean }) { const [caseType, setCaseType] = useState<"kyc" | "sanctions" | "transaction_monitoring" | "travel_rule" | "counterparty" | "sar_str">("sanctions"); const [severity, setSeverity] = useState<"low" | "medium" | "high" | "critical">("high"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ caseType, status: "open", severity, sourceReference: String(d.get("sourceReference")), decisionReason: String(d.get("decisionReason")) || undefined }); }}><Field label="Case type"><Select value={caseType} onValueChange={value => setCaseType(value as typeof caseType)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["kyc", "sanctions", "transaction_monitoring", "travel_rule", "counterparty", "sar_str"].map(value => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Severity"><Select value={severity} onValueChange={value => setSeverity(value as typeof severity)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["low", "medium", "high", "critical"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Verified source reference URL"><Input name="sourceReference" required type="url" className="rounded-none" /></Field><Field label="Review note"><Input name="decisionReason" className="rounded-none" /></Field></FormShell>; }
function ReportForm({ submit, pending }: { submit: (input: { regulator: "CBN" | "CBK" | "SARB"; corridor: "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR"; reportType: string; periodStart: Date; periodEnd: Date }) => void; pending: boolean }) { const [corridor, setCorridor] = useState("NIGERIA_NGN"); const [regulator, setRegulator] = useState<"CBN" | "CBK" | "SARB">("CBN"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); submit({ regulator, corridor: corridor as "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR", reportType: String(d.get("reportType")), periodStart: new Date(String(d.get("periodStart"))), periodEnd: new Date(String(d.get("periodEnd"))) }); }}><Field label="Regulator"><Select value={regulator} onValueChange={value => setRegulator(value as typeof regulator)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="CBN">CBN</SelectItem><SelectItem value="CBK">CBK</SelectItem><SelectItem value="SARB">SARB</SelectItem></SelectContent></Select></Field><Field label="Corridor"><CorridorSelect value={corridor} onValueChange={setCorridor} /></Field><Field label="Report type"><Input name="reportType" required placeholder="e.g. cross-border payment report" className="rounded-none" /></Field><Field label="Period start"><Input name="periodStart" required type="date" className="rounded-none" /></Field><Field label="Period end"><Input name="periodEnd" required type="date" className="rounded-none" /></Field></FormShell>; }
function AlertForm({ submit, pending }: { submit: (input: { alertType: "liquidity_threshold" | "payment_failure" | "compliance_flag" | "regulatory_deadline"; corridor?: "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR"; threshold: Record<string, unknown>; enabled: boolean }) => void; pending: boolean }) { const [alertType, setAlertType] = useState<"liquidity_threshold" | "payment_failure" | "compliance_flag" | "regulatory_deadline">("liquidity_threshold"); const [corridor, setCorridor] = useState("NIGERIA_NGN"); return <FormShell pending={pending} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); const raw = String(d.get("threshold")); try { submit({ alertType, corridor: corridor as "NIGERIA_NGN" | "KENYA_KES" | "SOUTH_AFRICA_ZAR", threshold: JSON.parse(raw), enabled: true }); } catch { toast.error("Threshold must be valid JSON, for example {\"minimum\":\"5000\"}"); } }}><Field label="Alert type"><Select value={alertType} onValueChange={value => setAlertType(value as typeof alertType)}><SelectTrigger className="rounded-none"><SelectValue /></SelectTrigger><SelectContent>{["liquidity_threshold", "payment_failure", "compliance_flag", "regulatory_deadline"].map(value => <SelectItem key={value} value={value}>{value.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field><Field label="Corridor"><CorridorSelect value={corridor} onValueChange={setCorridor} /></Field><Field label="Threshold JSON"><Input name="threshold" required defaultValue='{"minimum":""}' className="rounded-none font-mono text-xs" /></Field></FormShell>; }
