import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, BadgeCheck, Building2, FileCheck2, Landmark, ShieldCheck, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

const audiences = [
  { icon: Building2, title: "Corporate payment teams", copy: "Bring procurement, treasury, supplier evidence, and accountable approvals into one clear operating path." },
  { icon: Landmark, title: "Banks and authorised dealers", copy: "Review the documents, approvals, and reconciliation evidence required around a controlled customer case." },
  { icon: UsersRound, title: "Liquidity and technology partners", copy: "Share licensing, technical-readiness, and controlled-test evidence without being represented as live before approval." },
  { icon: ShieldCheck, title: "Compliance and oversight teams", copy: "Follow attributable decisions, evidence references, separation of duties, and review history without searching across disconnected systems." },
];

const corridors = [
  ["Nigeria", "NGN", "CBN", "Evidence-led onboarding, authorised-dealer coordination, and controlled readiness for cross-border cases."],
  ["Kenya", "KES", "CBK", "A shared view of accountable parties, required records, and review milestones for Kenya-linked flows."],
  ["South Africa", "ZAR", "SARB", "A structured control layer for treasury, supplier-payment, and regulatory evidence requirements."],
];

const partnerReadiness = [
  ["01", "Confirm your standing", "Share the licensing, legal-entity, and jurisdiction evidence your organisation is authorised to provide."],
  ["02", "Show operational readiness", "Record the technical contacts, safeguarding information, review route, and controlled-test evidence relevant to your role."],
  ["03", "Wait for independent review", "UmojaFlowOS keeps the review trail clear. A request is not an activation, a payment instruction, or a promise of access."],
];

const firstSteps = [
  ["Corporate teams", "Start a controlled case with your procurement context, intended corridor, supplier records, and accountable approvers."],
  ["Banks and authorised dealers", "Review the customer case, supporting records, authorised-dealer responsibilities, and reconciliation expectations."],
  ["Partners and suppliers", "Present your legal, technical, or beneficiary evidence in the workspace assigned to your organisation—without needing access to unrelated records."],
  ["Oversight and review teams", "Follow records, exceptions, decisions, and final reconciliation through a read-appropriate view."],
];

export default function PublicLanding() {
  const [, setLocation] = useLocation();
  return <main className="min-h-screen bg-[#f4f4f1] text-black">
    <header className="border-b border-black/20 bg-white">
      <div className="mx-auto flex max-w-[1440px] items-center justify-between gap-5 px-5 py-5 sm:px-8">
        <button aria-label="UmojaFlowOS home" onClick={() => setLocation("/")} className="flex items-center gap-3 text-left"><span className="flex h-10 w-10 items-center justify-center bg-[#e11919] text-sm font-black text-white">UF</span><span><span className="block text-sm font-black tracking-[-0.04em]">UMOJAFLOWOS</span><span className="block text-[10px] font-black uppercase tracking-[0.14em] text-black/45">Cross-border payment control</span></span></button>
        <nav className="hidden items-center gap-6 text-xs font-black uppercase tracking-[0.08em] md:flex" aria-label="Public navigation"><a href="#who-it-serves" className="hover:text-[#e11919]">Who it serves</a><a href="#partner-readiness" className="hover:text-[#e11919]">For partners</a><a href="#corridors" className="hover:text-[#e11919]">Markets</a><a href="#how-it-works" className="hover:text-[#e11919]">How it works</a></nav>
        <div className="flex items-center gap-2"><Button variant="outline" onClick={() => setLocation("/enroll")} className="rounded-none border-black/25 text-xs font-black uppercase">Start onboarding</Button><Button onClick={startLogin} className="rounded-none bg-black text-xs font-black uppercase hover:bg-[#e11919]">Sign in</Button></div>
      </div>
    </header>

    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.2fr_0.8fr] lg:py-24">
      <div><p className="uf-kicker">A clearer way to coordinate complex cross-border payments</p><h1 className="mt-4 max-w-5xl text-5xl font-black uppercase leading-[0.9] tracking-[-0.08em] sm:text-7xl">Keep every accountable party on the same page.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-black/65">UmojaFlowOS helps organisations organise payment readiness, supporting records, independent decisions, and final reconciliation across Africa-linked corridors. It does not replace your bank, authorised dealer, custody provider, or regulator.</p><div className="mt-9 flex flex-wrap gap-3"><Button size="lg" onClick={() => setLocation("/enroll")} className="rounded-none bg-[#e11919] text-xs font-black uppercase hover:bg-black">Find your role <ArrowRight className="ml-2 h-4 w-4" /></Button><Button size="lg" variant="outline" onClick={() => setLocation("/ng")} className="rounded-none border-black/25 text-xs font-black uppercase">Explore Nigeria, Kenya, and South Africa</Button></div></div>
      <div className="border border-black/25 bg-black p-6 text-white sm:p-8"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-white/55">The promise is control, not a shortcut</p><div className="mt-8 space-y-0">{[["01", "Start with real records", "Cases begin with attributable documents and references, not assumptions."], ["02", "Bring the right people in", "Each participant sees only the workspace and decisions assigned to them."], ["03", "Keep high-impact steps accountable", "Evidence, reviews, exceptions, and final reconciliation remain traceable."], ["04", "Activate nothing by default", "Payment, FX, stablecoin, and regulatory actions stay unavailable until independently authorised."]].map(([number, title, copy]) => <div className="border-t border-white/20 py-5" key={number}><div className="flex gap-4"><span className="text-sm font-black text-[#f14a4a]">{number}</span><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-sm leading-6 text-white/65">{copy}</p></div></div></div>)}</div></div>
    </section>

    <section id="who-it-serves" className="border-y border-black/20 bg-white"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8"><div className="max-w-3xl"><p className="uf-kicker">Built around the people who carry accountability</p><h2 className="mt-3 text-4xl font-black uppercase tracking-[-0.065em] sm:text-5xl">One shared picture. Clear individual responsibility.</h2></div><div className="mt-10 grid gap-px border border-black/20 bg-black sm:grid-cols-2">{audiences.map(({ icon: Icon, title, copy }) => <article key={title} className="bg-white p-6"><Icon className="h-6 w-6 text-[#e11919]" /><h3 className="mt-12 text-xl font-black tracking-[-0.04em]">{title}</h3><p className="mt-3 max-w-md text-sm leading-6 text-black/65">{copy}</p></article>)}</div></div></section>

    <section id="partner-readiness" className="border-b border-black/20 bg-[#111111] text-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-white/55">For financial, liquidity, technology, and supplier partners</p><h2 className="mt-3 text-4xl font-black uppercase leading-[0.9] tracking-[-0.065em] sm:text-5xl">Partner readiness begins with evidence.</h2><p className="mt-6 max-w-md text-sm leading-6 text-white/65">Share what your organisation can substantiate. The platform keeps your evidence, review route, and scope visible without presenting a relationship, service, or transaction as live before it is independently approved.</p><Button onClick={() => setLocation("/enroll")} variant="outline" className="mt-8 rounded-none border-white/40 text-xs font-black uppercase text-white hover:border-white hover:bg-white hover:text-black">Start partner onboarding <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="grid gap-px border border-white/25 bg-white/25 sm:grid-cols-3">{partnerReadiness.map(([number, title, copy]) => <article className="bg-[#111111] p-6" key={title}><span className="text-sm font-black text-[#f14a4a]">{number}</span><h3 className="mt-12 text-lg font-black leading-5">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{copy}</p></article>)}</div></div></section>

    <section id="corridors" className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-3xl"><p className="uf-kicker">Designed for Africa-linked corridors</p><h2 className="mt-3 text-4xl font-black uppercase tracking-[-0.065em] sm:text-5xl">Start locally. Coordinate globally.</h2></div><p className="max-w-sm text-sm leading-6 text-black/60">The platform explicitly supports control approaches for Nigeria (NGN), Kenya (KES), and South Africa (ZAR), with CBN, CBK, and SARB context visible where it is relevant.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{corridors.map(([country, currency, regulator, copy]) => <article key={country} className="border border-black/25 bg-white p-6"><div className="flex items-start justify-between"><span className="text-4xl font-black tracking-[-0.07em]">{currency}</span><BadgeCheck className="h-6 w-6 text-[#e11919]" /></div><p className="mt-10 text-[10px] font-black uppercase tracking-[0.14em] text-black/45">{regulator} context</p><h3 className="mt-2 text-2xl font-black tracking-[-0.04em]">{country}</h3><p className="mt-3 text-sm leading-6 text-black/65">{copy}</p></article>)}</div></section>

    <section id="how-it-works" className="bg-[#e11919] text-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[10px] font-black uppercase tracking-[0.14em] text-white/60">A simple starting point</p><h2 className="mt-3 text-4xl font-black uppercase leading-[0.9] tracking-[-0.07em] sm:text-5xl">You do not need to be a payments specialist to get started.</h2></div><div className="grid gap-px bg-white/35 sm:grid-cols-3">{[["Tell us your role", "Choose the responsibility you hold in a corporate, partner, supplier, or review team."], ["Prepare your evidence", "The platform explains the records your role can provide or review."], ["Wait for approval", "Access follows administrator and compliance review. Nothing is activated automatically."]].map(([title, copy], index) => <div className="bg-[#e11919] p-6" key={title}><span className="text-sm font-black text-white/60">0{index + 1}</span><h3 className="mt-10 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-white/75">{copy}</p></div>)}</div></div></section>

    <section className="border-b border-black/20 bg-white"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8"><div className="flex flex-col gap-5 border-b border-black/20 pb-8 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><p className="uf-kicker">What happens after you enrol</p><h2 className="mt-3 text-4xl font-black uppercase tracking-[-0.065em] sm:text-5xl">A clear next step for every role.</h2></div><p className="max-w-sm text-sm leading-6 text-black/60">Your first workspace is determined by your assigned role and approval status. It is not an open route into payments, accounts, or partner systems.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{firstSteps.map(([title, copy], index) => <article key={title} className="border-l-4 border-[#e11919] bg-[#f4f4f1] p-6"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-black/45">Starting point 0{index + 1}</p><h3 className="mt-8 text-xl font-black tracking-[-0.04em]">{title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-black/65">{copy}</p></article>)}</div></div></section>

    <footer className="border-t border-black/20 bg-white"><div className="mx-auto flex max-w-[1440px] flex-col gap-5 px-5 py-8 text-sm sm:px-8 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-2"><FileCheck2 className="h-4 w-4 text-[#e11919]" /><p className="text-black/60">UmojaFlowOS records readiness and accountability. It does not claim external execution before authorisation.</p></div><Button onClick={() => setLocation("/enroll")} className="rounded-none bg-black text-xs font-black uppercase hover:bg-[#e11919]">Begin stakeholder onboarding <ArrowRight className="ml-2 h-4 w-4" /></Button></div></footer>
  </main>;
}
