import { StakeholderPortalGallery } from "@/components/StakeholderPortal";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function StakeholderOnboarding() {
  const [, setLocation] = useLocation();
  return <main className="min-h-screen bg-[#f4f4f1] text-black">
    <header className="border-b border-black/20 bg-white"><div className="mx-auto flex max-w-[1440px] items-center justify-between gap-5 px-5 py-5 sm:px-8"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center bg-[#e11919] text-sm font-black text-white">UF</span><div><p className="text-sm font-black tracking-[-0.04em]">UMOJAFLOWOS</p><p className="text-[10px] font-black uppercase tracking-[0.14em] text-black/45">Africa-linked cross-border controls</p></div></div><Button onClick={() => startLogin()} className="rounded-none bg-black text-xs font-black uppercase hover:bg-[#e11919]">Sign in <ArrowRight className="ml-2 h-4 w-4" /></Button></div></header>
    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.15fr_0.85fr] lg:py-20"><div><p className="uf-kicker">Stakeholder onboarding</p><h1 className="mt-3 max-w-4xl text-5xl font-black uppercase leading-[0.92] tracking-[-0.075em] sm:text-7xl">Start with your operating role.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-black/65">UmojaFlowOS introduces the six stakeholder workspaces before operational access. Review the intended evidence, decision scope, and authority boundary, then sign in to reach only the workspace assigned to you.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => startLogin()} size="lg" className="rounded-none bg-[#e11919] text-xs font-black uppercase hover:bg-black">Access assigned workspace <ArrowRight className="ml-2 h-4 w-4" /></Button><Button variant="outline" onClick={() => setLocation("/console")} size="lg" className="rounded-none border-black/25 text-xs font-black uppercase">Operator sign-in</Button></div><div className="mt-12 border-l-4 border-[#e11919] bg-white p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#e11919]" /><p className="text-sm leading-6 text-black/70"><strong className="text-black">Authority remains protected.</strong> This onboarding page does not expose records, impersonate a stakeholder, activate a provider, submit to a regulator, execute a payment, or settle value. Those controls appear only after authentication and canonical PostgreSQL role resolution.</p></div></div></div><div className="border border-black/20 bg-white p-6"><p className="uf-kicker">Before you sign in</p><ol className="mt-6 space-y-5 text-sm leading-6 text-black/65"><li><span className="mr-3 inline-flex h-6 w-6 items-center justify-center bg-black text-[10px] font-black text-white">01</span>Identify the workspace that matches your accountable responsibility.</li><li><span className="mr-3 inline-flex h-6 w-6 items-center justify-center bg-black text-[10px] font-black text-white">02</span>Prepare only the evidence your role is permitted to record or review.</li><li><span className="mr-3 inline-flex h-6 w-6 items-center justify-center bg-black text-[10px] font-black text-white">03</span>Sign in. The operational console resolves your actual role from canonical PostgreSQL.</li></ol></div></section>
    <section className="mx-auto max-w-[1440px] px-5 pb-20 sm:px-8"><StakeholderPortalGallery /></section>
  </main>;
}
